
## CLASIFICACIÓN DEL RIESGO DE ABANDONO DE LOS CLIENTES DE UN BANCO

El conjunto de datos con el que vamos a trabajar ahora contiene información sobre los usuarios de un banco. Queremos predecir si los clientes van a dejar de usar los servicios de dicho banco o no. El conjunto de datos consta de 10000 observaciones y 14 variables.

La siguiente figura indica cómo cargar el conjunto de Datos:

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd


In [2]:
dataset = pd.read_csv('Churn_Modelling.csv')

In [3]:
dataset.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

Creamos una matriz con las variables de entrada y otra matriz con la variable de salida (objetivo, columna 14). Excluiremos la columna 1 y 2 que son ‘row_number’ y ‘customerid’ ya que no nos aportan información útil para el análisis.

In [4]:
X = dataset.iloc[:,3:13].values

In [5]:
X[0:4]

array([[619, 'France', 'Female', 42, 2, 0.0, 1, 1, 1, 101348.88],
       [608, 'Spain', 'Female', 41, 1, 83807.86, 1, 0, 1, 112542.58],
       [502, 'France', 'Female', 42, 8, 159660.8, 3, 1, 0, 113931.57],
       [699, 'France', 'Female', 39, 1, 0.0, 2, 0, 0, 93826.63]],
      dtype=object)

In [6]:
y = dataset.iloc[:,13].values

Vamos a hacer el análisis más sencillo si codificamos las variables no numéricas. Country contiene los valores: ’France, Spain, Germany’ y Gender: ‘Male, Female’. La manera de codificarlo será convertir estas palabras a valores numéricos. Para esto usaremos la función LabelEncoder, de la librería ‘ScikitLearn’, que al darle una cadena de texto nos devuelve valores entre 0 y n_clases-1.

In [7]:
from sklearn.preprocessing import LabelEncoder
labelencoder_X_1 = LabelEncoder()
X[:, 1] = labelencoder_X_1.fit_transform(X[:, 1])
labelencoder_X_2 = LabelEncoder()
X[:, 2] = labelencoder_X_2.fit_transform(X[:, 2])

In [8]:
X

array([[619, 0, 0, ..., 1, 1, 101348.88],
       [608, 2, 0, ..., 0, 1, 112542.58],
       [502, 0, 0, ..., 1, 0, 113931.57],
       ...,
       [709, 0, 0, ..., 0, 1, 42085.58],
       [772, 1, 1, ..., 1, 0, 92888.52],
       [792, 0, 0, ..., 1, 0, 38190.78]], dtype=object)

Observamos que Country ahora toma valores del 0 al 2 mientras que male y female fueron reemplazados por 0 y 1.

Usaremos la función train_test_split de la librería ScikitLearn para dividir nuestros datos.

Usaremos 80% para entrenar el modelo y 20% para validarlo.

In [9]:
from sklearn.model_selection import train_test_split

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state=42)

In [11]:
X_train, X_test, y_train, y_test

(array([[696, 0, 1, ..., 0, 0, 126353.13],
        [635, 2, 1, ..., 1, 1, 60739.16],
        [585, 1, 1, ..., 1, 1, 112333.22],
        ...,
        [742, 0, 0, ..., 1, 1, 180066.59],
        [802, 1, 0, ..., 0, 1, 169183.66],
        [774, 2, 0, ..., 0, 0, 108804.28]], dtype=object),
 array([[794, 1, 0, ..., 1, 0, 160526.36],
        [624, 0, 0, ..., 1, 0, 168002.31],
        [759, 0, 1, ..., 0, 1, 121409.06],
        ...,
        [589, 1, 0, ..., 1, 1, 143022.31],
        [652, 2, 1, ..., 0, 1, 170025.43],
        [565, 0, 0, ..., 1, 1, 168303.55]], dtype=object),
 array([1, 0, 0, ..., 0, 0, 0], dtype=int64),
 array([1, 1, 0, ..., 1, 0, 0], dtype=int64))

Si observamos los datos detenidamente podemos apreciar que hay variables cuyos valores pueden
ser muy variados, desde muy altos a muy pequeños por esta razón escalaremos los datos.

In [12]:
from sklearn.preprocessing import StandardScaler

In [13]:
sc = StandardScaler()

In [14]:
X_train = sc.fit_transform(X_train)

In [15]:
X_test = sc.transform(X_test)

In [16]:
X_train, X_test, y_train, y_test

(array([[ 0.47570015, -0.90354823,  0.9171678 , ..., -1.55196866,
         -1.03227043,  0.44797438],
        [-0.15694707,  1.51074229,  0.9171678 , ...,  0.64434291,
          0.9687384 , -0.69291758],
        [-0.67551037,  0.30359703,  0.9171678 , ...,  0.64434291,
          0.9687384 ,  0.20419699],
        ...,
        [ 0.95277839, -0.90354823, -1.09031302, ...,  0.64434291,
          0.9687384 ,  1.38194096],
        [ 1.57505435,  0.30359703, -1.09031302, ..., -1.55196866,
          0.9687384 ,  1.19270919],
        [ 1.2846589 ,  1.51074229, -1.09031302, ..., -1.55196866,
         -1.03227043,  0.14283598]]),
 array([[ 1.49208422,  0.30359703, -1.09031302, ...,  0.64434291,
         -1.03227043,  1.04217655],
        [-0.271031  , -0.90354823, -1.09031302, ...,  0.64434291,
         -1.03227043,  1.17216794],
        [ 1.12908991, -0.90354823,  0.9171678 , ..., -1.55196866,
          0.9687384 ,  0.36200717],
        ...,
        [-0.63402531,  0.30359703, -1.09031302, ...,  

Una vez escalados los datos, pasamos a construir la red neuronal. Importamos Keras, usamos el módulo Sequential para inicializar la red y el modelo Dense para añadir capas ocultas.

In [17]:
import tensorflow as tf

from tensorflow.keras.layers import Dense
from tensorflow.keras import Sequential

Inicializamos la red con Sequential().

In [18]:
classifier = Sequential()

Añadimos las capas usando la función Dense. Indicamos el número de nodos que queremos añadir con output_dim, Init es la inicialización del descenso de gradiente estocástico. Los pesos iniciales serán una variable aleatoria uniforme. Input_dim sólo es necesaria en la primera capa para que el modelo sepa la cantidad de variables que va a recibir, en nuestro caso 11. A partir de aquí las siguientes capas heredarán esta cualidad de la primera capa. La función de activación que utilizaremos será relu en las dos primeras capas (cuanto más cerca tenga su valor a 1, la neurona estará más activada y tendrá más interacción) y en la capa final hemos utilizado la función sigmoide ya que nuestro objetivo es clasificar.

Una vez que tenemos la configuración específica de la red, la siguiente tarea es compilarla, para eso utilizamos la función Compile. El primer argumento de esta función es Optimizer que indica el método para entrenar los pesos. Adam es un algoritmo que se basa en el cálculo del descenso del Gradiente Estocástico. El segundo parámetro es loss, este usará la función ‘binary_crossentropy’ para clasificar en 2 categorías. Si tuviéramos más categorías utilizaríamos la función ‘categorical_crossentropy’. Para saber la bondad de nuestra red neuronal utilizaremos la métrica accuracy.

In [19]:
classifier.add(Dense(6, activation = 'relu', input_shape = (10,)))

In [20]:
classifier.add(Dense(6, activation = 'relu'))

In [21]:
classifier.add(Dense(1, activation = 'sigmoid'))

In [22]:
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy']) 

Usaremos la función fit para ajustar los pesos de la red. Batch_size para especificar el número de observaciones que necesita entrenar antes de actualizar los pesos. Epoch nos indica el número de iteraciones que realizaremos en el entrenamiento. La estimación de estos parámetros se tiene que hacer por ensayo-error, probando con diferentes valores.

In [23]:
classifier.fit(X_train, y_train, epochs=100, batch_size=1, verbose=1)

Epoch 1/100


8000/8000 [==============================] - 7s 778us/step - loss: 0.4490 - accuracy: 0.8060
Epoch 2/100
8000/8000 [==============================] - 6s 781us/step - loss: 0.3904 - accuracy: 0.8378
Epoch 3/100
8000/8000 [==============================] - 6s 785us/step - loss: 0.3655 - accuracy: 0.8497
Epoch 4/100
8000/8000 [==============================] - 6s 788us/step - loss: 0.3576 - accuracy: 0.8512
Epoch 5/100
8000/8000 [==============================] - 6s 789us/step - loss: 0.3520 - accuracy: 0.8543
Epoch 6/100
8000/8000 [==============================] - 6s 790us/step - loss: 0.3495 - accuracy: 0.8566
Epoch 7/100
8000/8000 [==============================] - 6s 788us/step - loss: 0.3488 - accuracy: 0.8560
Epoch 8/100
8000/8000 [==============================] - 6s 789us/step - loss: 0.3487 - accuracy: 0.8559
Epoch 9/100
8000/8000 [==============================] - 6s 792us/step - loss: 0.3475 - accuracy: 0.8559
Epoch 10/100
8000/8000 [=============================

Para realizar la predicción sobre nuestro conjunto de test lo haremos mediante la siguiente expresión:

In [24]:
y_pred = classifier.predict(X_test)

63/63 [==============================] - 0s 756us/step


In [25]:
y_pred = (y_pred > 0.5)

La predicción nos proporcionará la probabilidad de pertenecer a un grupo u otro, de tal manera que aquellos valores mayores que 0.5 serán 1 y el resto 0.

Creamos una matriz de confusión y vemos los resultados:

In [26]:
from sklearn.metrics import confusion_matrix

In [27]:
cm = confusion_matrix(y_test, y_pred)
cm

array([[1518,   86],
       [ 214,  182]], dtype=int64)

In [28]:
import sklearn.metrics as metrics
print(metrics.classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.88      0.95      0.91      1604
           1       0.68      0.46      0.55       396

    accuracy                           0.85      2000
   macro avg       0.78      0.70      0.73      2000
weighted avg       0.84      0.85      0.84      2000



# Ejercicio: Búsqueda del mejor modelo.

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:,3:13].values
y = dataset.iloc[:,13].values
labelencoder_X_1 = LabelEncoder()
X[:, 1] = labelencoder_X_1.fit_transform(X[:, 1])
labelencoder_X_2 = LabelEncoder()
X[:, 2] = labelencoder_X_2.fit_transform(X[:, 2])
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state=42)
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [6]:
# To be able to import the sklear-wrapper
# !pip install scikeras
# !pip uninstall -y scikit-learn
# !pip install scikit-learn==1.5.2

Found existing installation: scikit-learn 1.6.1
Uninstalling scikit-learn-1.6.1:
  Successfully uninstalled scikit-learn-1.6.1
  Using cached scikit_learn-1.5.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (13.3 MB)

[notice] A new release of pip is available: 23.0.1 -> 24.3.1
[notice] To update, run: pip install --upgrade pip


In [12]:
import numpy as np
import keras 
from keras.layers import Input, Dense, Dropout
from keras import Sequential
from scikeras.wrappers import KerasClassifier
from sklearn.model_selection import GridSearchCV
np.random.seed(140421)
keras.utils.set_random_seed(140421)

def get_model(
  optimizer = None,
  activation="relu",
  layer_config = None,
):
  if not layer_config:
    layer_config = [(32, 0.1), (64, .2), (32, .2)]
  if not optimizer:
    optimizer = lambda: keras.optimizers.RMSprop()
  optimizer = optimizer()
  model = Sequential()
  model.add(Input(10))
  for layer in layer_config:
    model.add(Dense(layer[0], activation=activation))
    if len(layer) > 0 and layer[1] > 0.0:
      model.add(Dropout(layer[1]))
  model.add(Dense(1, activation="sigmoid"))
  return model

fit_params = {
  "callbacks": [
    keras.callbacks.EarlyStopping(patience=5, restore_best_weights=True),
    keras.callbacks.ReduceLROnPlateau(),
  ]
}

# sk_model = KerasClassifier(build_fn=get_model)
sk_model = KerasClassifier(
    get_model,
    loss="binary_crossentropy",
    metrics=[
      "accuracy"
#       keras.metrics.F1Score(),
#       keras.metrics.Recall(),
#       keras.metrics.Precision(),
#       keras.metrics.Accuracy()
    ]
)

optimizers = [
  lambda: keras.optimizers.AdamW(
    learning_rate=keras.optimizers.schedules.ExponentialDecay()
  ),
]
activation = ["relu", "leaky_relu", "tanh"]
epochs = 20
batches = [1, 16, 32]
param_grid = dict(optimizer=optimizers)
grid = GridSearchCV(estimator=sk_model, param_grid=param_grid, refit=False, cv=3, scoring="accuracy")
grid_result = grid.fit(X_train, y_train)

ValueError: 
All the 3 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "/home/briansenas/Master/SoftComputing/Optimizacion/guiones/Guion 2-20250110/.venv/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 888, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/briansenas/Master/SoftComputing/Optimizacion/guiones/Guion 2-20250110/.venv/lib/python3.10/site-packages/scikeras/wrappers.py", line 1501, in fit
    super().fit(X=X, y=y, sample_weight=sample_weight, **kwargs)
  File "/home/briansenas/Master/SoftComputing/Optimizacion/guiones/Guion 2-20250110/.venv/lib/python3.10/site-packages/scikeras/wrappers.py", line 770, in fit
    self._fit(
  File "/home/briansenas/Master/SoftComputing/Optimizacion/guiones/Guion 2-20250110/.venv/lib/python3.10/site-packages/scikeras/wrappers.py", line 925, in _fit
    X, y = self._initialize(X, y)
  File "/home/briansenas/Master/SoftComputing/Optimizacion/guiones/Guion 2-20250110/.venv/lib/python3.10/site-packages/scikeras/wrappers.py", line 862, in _initialize
    self.model_ = self._build_keras_model()
  File "/home/briansenas/Master/SoftComputing/Optimizacion/guiones/Guion 2-20250110/.venv/lib/python3.10/site-packages/scikeras/wrappers.py", line 433, in _build_keras_model
    model = final_build_fn(**build_params)
  File "/tmp/ipykernel_2333713/1338524737.py", line 21, in get_model
    model.add(Input(10))
  File "/home/briansenas/Master/SoftComputing/Optimizacion/guiones/Guion 2-20250110/.venv/lib/python3.10/site-packages/keras/src/layers/core/input_layer.py", line 191, in Input
    layer = InputLayer(
  File "/home/briansenas/Master/SoftComputing/Optimizacion/guiones/Guion 2-20250110/.venv/lib/python3.10/site-packages/keras/src/layers/core/input_layer.py", line 92, in __init__
    shape = backend.standardize_shape(shape)
  File "/home/briansenas/Master/SoftComputing/Optimizacion/guiones/Guion 2-20250110/.venv/lib/python3.10/site-packages/keras/src/backend/common/variables.py", line 562, in standardize_shape
    raise ValueError(f"Cannot convert '{shape}' to a shape.")
ValueError: Cannot convert '10' to a shape.
