__Nombre__: Brian Sena Simons

## Ejercicios
Se pueden hacer todos sin necesidad de bucles explícitos... pensad... pensad...

1. Crear una función "creciente" que indique si los elementos de un array dado son estrictamente crecientes. No se permite ordenar el vector.

In [308]:
creciente <- function(vec) {
  displacement <- vec[2:length(vec)]
  sum(vec[1: length(vec)-1] <= displacement) == length(vec) - 1
}

print(creciente(1:10))  # TRUE
print(creciente(10:1))  # FALSE
print(creciente(c(1:5, 10:6))) # FALSE
print(creciente(1:1))  # TRUE
print(creciente(c()))  # FALSE

[1] TRUE
[1] FALSE
[1] FALSE
[1] TRUE
[1] FALSE


2. Crear una función "montecarlo" que calcule la estimación de la integral dada:
 >$\int_{0}^{1} x^2 dx$<br/>
   
   El algoritmo Monte Carlo en pseudocódigo es el siguiente:
>hits=0<br/>
 for i from 1 to N<br/>
 &nbsp;&nbsp;&nbsp;&nbsp;Generate two random numbers r1 and r2 between 0 and 1<br/>
 &nbsp;&nbsp;&nbsp;&nbsp;If r2<r1^2 then hits=hits+1<br/>
 end for<br/>
 return hits/N

    HINT: Use las funciones `runif()` y `rnorm()`.

In [309]:
monte_carlo <- function(n) {
  r1 <- runif(n, 0, 1)
  r2 <- runif(n, 0, 1)
  hits <- sum(ifelse(r2 < r1**2, 1, 0))
  hits / n
}
monte_carlo(10000)

[1] 0.3293

3. Crea una lista de cinco matrices numéricas y ordénalas tras su creación
(el elemento [1,1] tendrá el valor menor y el [#filas,#columnas] el valor mayor).

In [310]:
random_matrix <- function(size, nrow, ncol) {
  matrix(
    sample(1:100, size, replace = TRUE),
    nrow = nrow,
    ncol = ncol
  )
}
lista <- list(
  random_matrix(9, 3, 3),
  random_matrix(10, 2, 5),
  random_matrix(4, 2, 2),
  random_matrix(21, 3, 7),
  random_matrix(9, 3, 3)
)

sorted_list_of_matrices <- function(lista) {
  lapply(
    lista,
    function(x) matrix(sort(x), nrow = nrow(x), ncol = ncol(x))
  )
}

print(sorted_list_of_matrices(lista))

[[1]]
     [,1] [,2] [,3]
[1,]   15   44   80
[2,]   23   58   85
[3,]   39   79   87

[[2]]
     [,1] [,2] [,3] [,4] [,5]
[1,]   36   45   52   73   77
[2,]   43   47   70   74   85

[[3]]
     [,1] [,2]
[1,]    1   52
[2,]   23   71

[[4]]
     [,1] [,2] [,3] [,4] [,5] [,6] [,7]
[1,]    8   18   23   41   60   68   81
[2,]   11   19   33   49   60   70   88
[3,]   13   21   38   51   61   79   99

[[5]]
     [,1] [,2] [,3]
[1,]   14   37   79
[2,]   14   51   90
[3,]   24   67   95



4. Calcula el valor mínimo de cada columna de una matriz, pero suponiendo que los números impares son negativos y los pares positivos.

In [311]:
funny_min_column <- function(N, ncol) {
  data <- matrix(1:N, ncol = ncol)
  # We set all values to positive
  data <- abs(data[, ])
  # We then fetch the position of the odds
  impares_index <- data %% 2 == 1
  # Now we can just multiply by -1
  data[impares_index] <- data[impares_index] * -1
  # Unfortunately I don't know if we can avoid the apply
  apply(data, 2, min)
}
N <- 10
ncol <- 5
data <- matrix(1:N, ncol = ncol)
print(data)
funny_min_column(N, ncol)

     [,1] [,2] [,3] [,4] [,5]
[1,]    1    3    5    7    9
[2,]    2    4    6    8   10


[1] -1 -3 -5 -7 -9

In [312]:
system.time(funny_min_column(10000000, 10000))

   user  system elapsed 
  0.434   0.057   0.495 

5. Dada una matriz devuelve una lista de todos los valores mayores que 7 de cada fila.

In [313]:
filter_value <- function(data, val = 7) {
  # No se me ocurre una forma vectorizada
  apply(data, 1, function(x) x[x > val])
}
data <- matrix(1:10, nrow = 2)
print(filter_value(data, 7))

[[1]]
[1] 9

[[2]]
[1]  8 10



# Anexo

In [314]:
filter_value2 <- function(data, val = 7) {
  filter_condition <- data > val
  # Sigue siendo una especie de bucle for...
  lapply(seq_len(nrow(data)), function(i) data[i, filter_condition[i, ]])
}
data <- matrix(1:10, nrow = 2)
print(filter_value2(data, 7))


[[1]]
[1] 9

[[2]]
[1]  8 10



In [315]:
filter_value3 <- function(data, val = 7) {
  mask <- data > val
  # This is super slow bro...
  split(data[mask], row(data)[mask])
}
data <- matrix(1:10, nrow = 2)
print(filter_value_vec(data, 7))

$`1`
[1] 9

$`2`
[1]  8 10

