# __Nombre__: Brian Sena Simons

# Ejercicios matrices y arrays

1) Dada la siguiente matrix:
<pre>laberinto <- matrix(c(
   "O", "X", "O", "O", "O",
   "O", "X", "X", "X", "O",
   "O", "O", "O", "O", "X",
   "X", "X", "X", "O", "X",
   "O", "O", "O", "O", "O"
 ), nrow = 5, byrow = TRUE)</pre>
    * Indique donde están las "X" usando la función `which`
    * Indique donde están las "X" usando la función `which` pero usando el parámetro `arr.ind`
    * Indique cuantos valores "X" hay en la matriz
    * Reemplace las "X" por 1 y los "O" por 0 y convierta la matrix en una matrix numérica
    * Indique si la matrix es simétrica
    * Cree una nueva matrix con los valores en las filas y columnas pares 

In [2]:
laberinto <- matrix(
  c(
    "O", "X", "O", "O", "O",
    "O", "X", "X", "X", "O",
    "O", "O", "O", "O", "X",
    "X", "X", "X", "O", "X",
    "O", "O", "O", "O", "O"
  ),
  nrow = 5, byrow = TRUE
)
print(x <- which(laberinto == "X", arr.ind = FALSE))
print(y <- which(laberinto == "X", arr.ind = TRUE))
print("Comprobamos los resultados que solo tenga X's:")
print(laberinto[x])
print("Comprobamos que es la misma longitud mirando en la matriz que con which")
print(length(laberinto[laberinto == "X"]) == length(laberinto[x]))
print(c("Número de X's:", length(laberinto[x])))

[1]  4  6  7  9 12 14 17 23 24
      row col
 [1,]   4   1
 [2,]   1   2
 [3,]   2   2
 [4,]   4   2
 [5,]   2   3
 [6,]   4   3
 [7,]   2   4
 [8,]   3   5
 [9,]   4   5
[1] "Comprobamos los resultados que solo tenga X's:"
[1] "X" "X" "X" "X" "X" "X" "X" "X" "X"
[1] "Comprobamos que es la misma longitud mirando en la matriz que con which"
[1] TRUE
[1] "Número de X's:" "9"             


In [7]:
print("Intercambiamos los X y O por 1 y 0 respectivamente")
shape <- dim(laberinto)
laberinto <- matrix(0, nrow = shape[1], ncol = shape[2])
laberinto[x] <- 1
print(laberinto)
print("Verificamos si la matriz es simétrica.")
print(all(laberinto == t(laberinto)))
print("La matriz NO es simétrica ya que A^t != A")
mpar <- matrix(0, nrow = shape[1], ncol = shape[2])
pares <- seq(2, shape[2], by = 2)
mpar[pares, pares] <- 2
print(mpar)

[1] "Intercambiamos los X y O por 1 y 0 respectivamente"
     [,1] [,2] [,3] [,4] [,5]
[1,]    0    1    0    0    0
[2,]    0    1    1    1    0
[3,]    0    0    0    0    1
[4,]    1    1    1    0    1
[5,]    0    0    0    0    0
[1] "Verificamos si la matriz es simétrica."
[1] FALSE
[1] "La matriz NO es simétrica ya que A^t != A"


     [,1] [,2] [,3] [,4] [,5]
[1,]    0    0    0    0    0
[2,]    0    2    0    2    0
[3,]    0    0    0    0    0
[4,]    0    2    0    2    0
[5,]    0    0    0    0    0


In [101]:
print("Una matriz simétrica sería p.e")
test <- matrix(c(7, 4, 4, 7), nrow = 2, ncol = 2)
print(test)
print(all(test == t(test)))

[1] "Una matriz simétrica sería p.e"
     [,1] [,2]
[1,]    7    4
[2,]    4    7
[1] TRUE


2) Crea una matriz que represente un Sudoku. Debe estar inicializada en NA. Luego rellenar solo un 10% de las casillas con un valor entre 1 y 9 (HINT: usa la función `sample`). No se preocupe de que sea un esquema válido (se pueden repetir valores en una fila por ejemplo... eso ya lo haremos más adelante...)

In [102]:
sudoku <- matrix(nrow = 9, ncol = 9)
fill_pos <- sample(seq(1, 81), size = 0.1 * length(sudoku))
values <- sample(seq(1, 9), size = 0.1 * length(sudoku))
sudoku[fill_pos] <- values
print(sudoku)

      [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9]
 [1,]   NA    9   NA   NA   NA   NA   NA   NA   NA
 [2,]    4   NA   NA   NA    8    5   NA   NA   NA
 [3,]   NA   NA   NA   NA   NA   NA   NA   NA   NA
 [4,]   NA   NA   NA   NA   NA   NA   NA   NA    3
 [5,]   NA   NA   NA   NA   NA   NA   NA   NA   NA
 [6,]   NA   NA   NA   NA   NA   NA   NA   NA   NA
 [7,]    6   NA   NA   NA   NA   NA   NA    7   NA
 [8,]   NA   NA   NA   NA   NA   NA   NA   NA   NA
 [9,]   NA   NA   NA   NA   NA   NA   NA   NA    1


3) Teniendo estas dos matrices:
<pre>matriz <- matrix(sample(1:9, 30,replace=TRUE), nrow=5)</pre>
<pre>mascara <- matrix(sample(c(TRUE,FALSE), 30, replace=TRUE), nrow=5)</pre>
    * Aplique la máscara a la matrix, en donde si la posicion en la máscara es FALSE entonces el resultado es 0 y sino se mantiene su valor
    * Calcule el producto de la matriz original por la matriz modificada traspuesta (NOTA: la matriz final será de 5x5)

In [103]:
matriz <- matrix(sample(1:9, 30, replace = TRUE), nrow = 5)
masked_matrix <- matriz
print(matriz)
mascara <- matrix(sample(c(TRUE, FALSE), 30, replace = TRUE), nrow = 5)
print(mascara)
masked_matrix[mascara] <- 0
print(masked_matrix)
matriz %*% t(masked_matrix)

     [,1] [,2] [,3] [,4] [,5] [,6]
[1,]    8    3    3    1    8    1
[2,]    4    5    2    3    2    3
[3,]    3    3    3    3    4    1
[4,]    1    2    4    1    9    5
[5,]    9    6    1    4    7    5
      [,1]  [,2]  [,3]  [,4]  [,5]  [,6]
[1,] FALSE FALSE  TRUE FALSE  TRUE  TRUE
[2,] FALSE FALSE  TRUE FALSE FALSE FALSE
[3,] FALSE FALSE FALSE FALSE FALSE FALSE
[4,] FALSE  TRUE  TRUE  TRUE  TRUE FALSE
[5,] FALSE FALSE  TRUE FALSE  TRUE FALSE
     [,1] [,2] [,3] [,4] [,5] [,6]
[1,]    8    3    0    1    0    0
[2,]    4    5    0    3    2    3
[3,]    3    3    3    3    4    1
[4,]    1    0    0    0    0    5
[5,]    9    6    0    4    0    5


[,1] [,2] [,3] [,4] [,5]
[1,] 74    69  78   13    99 
[2,] 50    63  53   19    93 
[3,] 36    47  53    8    62 
[4,] 15    50  65   26    50 
[5,] 94   107  93   34   158

4) Crea un array 5D llamado "mi_array5D" con las siguientes características, rellénalo con números enteros consecutivos comenzando desde 1:
    - Tamaño de la primera dimensión: 2 elementos
    - Tamaño de la segunda dimensión: 3 elementos
    - Tamaño de la tercera dimensión: 4 elementos
    - Tamaño de la cuarta dimensión: 5 elementos
    - Tamaño de la quinta dimensión: 6 elementos
    
    4.1) Accede a los siguientes elementos del array:
    * los elementos pares (analice la posición de esos valores en las 5 dimensiones)
    * estudiando el caso anterior muestre los elementos impares sin usar ningun tipo de condicional, igualdad o desigualdad
    
    4.2) Redimensiona el array para que tenga:
    - Tamaño de la primera dimensión: 6 elementos.
    - Tamaño de la segunda dimensión: 5 elementos.
    - Tamaño de la tercera dimensión: 4 elementos.
    - Tamaño de la cuarta dimensión: 3 elementos.
    - Tamaño de la quinta dimensión: 2 elementos.

In [104]:
mi_array5d <- array(
  data = seq(from = 1, to = 2 * 3 * 4 * 5 * 6, by = 1), dim = c(2, 3, 4, 5, 6)
)
print("Visualizamos la última dimensión:")
print(mi_array5d[1, 1, 1, 1,])
print("Visualizamos la cuarta dimensión")
print(mi_array5d[1, 1, 1, ,])
print(
  c(
    "Longitud total:",
    length(mi_array5d),
    "Longitud última dimensión:",
    length(mi_array5d[1, 1, 1, 1,]),
    "Longitud cuarta dimensión:",
    length(mi_array5d[1, 1, 1, ,])
  )
)
print("Accedemos a los elementos pares: ")
pares <- seq(from = 2, to = length(mi_array5d), by = 2)
print(mi_array5d[pares])

[1] "Visualizamos la última dimensión:"
[1]   1 121 241 361 481 601
[1] "Visualizamos la cuarta dimensión"
     [,1] [,2] [,3] [,4] [,5] [,6]
[1,]    1  121  241  361  481  601
[2,]   25  145  265  385  505  625
[3,]   49  169  289  409  529  649
[4,]   73  193  313  433  553  673
[5,]   97  217  337  457  577  697
[1] "Longitud total:"            "720"                       
[3] "Longitud última dimensión:" "6"                         
[5] "Longitud cuarta dimensión:" "30"                        
[1] "Accedemos a los elementos pares: "
  [1]   2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34  36
 [19]  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70  72
 [37]  74  76  78  80  82  84  86  88  90  92  94  96  98 100 102 104 106 108
 [55] 110 112 114 116 118 120 122 124 126 128 130 132 134 136 138 140 142 144
 [73] 146 148 150 152 154 156 158 160 162 164 166 168 170 172 174 176 178 180
 [91] 182 184 186 188 190 192 194 196 198 200 202 204 206 208 210 2

In [105]:
print(mi_array5d[pares - 1])

  [1]   1   3   5   7   9  11  13  15  17  19  21  23  25  27  29  31  33  35
 [19]  37  39  41  43  45  47  49  51  53  55  57  59  61  63  65  67  69  71
 [37]  73  75  77  79  81  83  85  87  89  91  93  95  97  99 101 103 105 107
 [55] 109 111 113 115 117 119 121 123 125 127 129 131 133 135 137 139 141 143
 [73] 145 147 149 151 153 155 157 159 161 163 165 167 169 171 173 175 177 179
 [91] 181 183 185 187 189 191 193 195 197 199 201 203 205 207 209 211 213 215
[109] 217 219 221 223 225 227 229 231 233 235 237 239 241 243 245 247 249 251
[127] 253 255 257 259 261 263 265 267 269 271 273 275 277 279 281 283 285 287
[145] 289 291 293 295 297 299 301 303 305 307 309 311 313 315 317 319 321 323
[163] 325 327 329 331 333 335 337 339 341 343 345 347 349 351 353 355 357 359
[181] 361 363 365 367 369 371 373 375 377 379 381 383 385 387 389 391 393 395
[199] 397 399 401 403 405 407 409 411 413 415 417 419 421 423 425 427 429 431
[217] 433 435 437 439 441 443 445 447 449 451 453 455 457 459 46

5) Supongamos que tenemos un grafo no dirigido con 6 nodos etiquetados del 1 al 6, y las siguientes aristas:
    * Arista 1: (1, 2)
    * Arista 2: (1, 3)
    * Arista 3: (2, 4)
    * Arista 4: (2, 5)
    * Arista 5: (3, 6)
    * Arista 6: (4, 5)
    
    Crea una matriz de adyacencia "matriz_adyacencia" en R para representar este grafo. En una matriz de adyacencia, las filas y columnas representan los nodos, y un valor 1 indica que existe una arista entre los nodos correspondientes, mientras que un valor 0 indica la ausencia de una arista.
    * Calcula el grado del nodo 4 en el grafo. El grado de un nodo es la cantidad de aristas que inciden en él
    * Encuentra todos los nodos adyacentes del nodo 2
    * Cuenta la cantidad de nodos que tiene una arista hacia si mismos (self-loop)

In [106]:
adjacency <- matrix(data = 0, nrow = 6, ncol = 6, byrow = TRUE)
i <- c(1, 1, 2, 2, 3, 4)
j <- c(2, 3, 4, 5, 6, 5)
adjacency[((i - 1) * 6) + j] <- 1
adjacency[((j - 1) * 6) + i] <- 1
print(adjacency)
print(c("Grado del nodo 4:", sum(adjacency[, 4])))
print("Nodos adyacientes al 2:")
print(which(adjacency[, 2] == 1, arr.ind = TRUE))
print("Suma de los nodos con un self-loop:")
print(sum(diag(adjacency) == 1))

     [,1] [,2] [,3] [,4] [,5] [,6]
[1,]    0    1    1    0    0    0
[2,]    1    0    0    1    1    0
[3,]    1    0    0    0    0    1
[4,]    0    1    0    0    1    0
[5,]    0    1    0    1    0    0
[6,]    0    0    1    0    0    0
[1] "Grado del nodo 4:" "2"                
[1] "Nodos adyacientes al 2:"
[1] 1 4 5
[1] "Suma de los nodos con un self-loop:"
[1] 0


In [107]:
# Si solo hubieramos rellenado las relaciones explícitcas
# Los nodos adyacientes serían:
adjacency <- matrix(data = 0, nrow = 6, ncol = 6, byrow = TRUE)
adjacency[((i - 1) * 6) + j] <- 1
print(
  c(
    which(adjacency[2, ] == 1, arr.ind = TRUE),
    which(adjacency[, 2] == 1, arr.ind = TRUE)
  )
)

[1] 1 4 5


In [108]:
# Para comprobar las operaciones anteriores:
test <- matrix(data = 1, nrow = 6, ncol = 6, byrow = TRUE)
print("Creamos un grafo de todos a todos, la suma de self-loop debería ser 6")
print(sum(diag(test) == 1) == 6)
print("El número de nodos adyacientes al 2 debería ser 6")
print(which(test[, 2] == 1, arr.ind = TRUE))

[1] "Creamos un grafo de todos a todos, la suma de self-loop debería ser 6"
[1] TRUE
[1] "El número de nodos adyacientes al 2 debería ser 6"
[1] 1 2 3 4 5 6
