# Introducción a la Programación para Ciencia de Datos
## Lenguaje de programación R
_Rocío Romero Zaliz_ - rocio@decsai.ugr.es

# Tipos de datos básicos

* numeric / integer
* logical
* complex
* character

In [1]:
print(1)

[1] 1


In [2]:
class(1)

[1] "numeric"

In [3]:
class(1.5)

[1] "numeric"

In [4]:
class(-3.78)

[1] "numeric"

In [5]:
TRUE

[1] TRUE

In [6]:
class(TRUE)

[1] "logical"

In [7]:
class(FALSE)

[1] "logical"

In [8]:
4 + 1.2i

[1] 4+1.2i

In [9]:
class(4 + 1.2i)

[1] "complex"

In [10]:
print("a")

[1] "a"


In [11]:
class("a")

[1] "character"

In [12]:
class("hola")

[1] "character"

In [13]:
class("adios") # Recomendado

[1] "character"

In [14]:
class('adios') # No recomendado

[1] "character"

In [15]:
"hola" y "adios" # Error

ERROR: Error in parse(text = x, srcfile = src): <text>:1:8: unexpected symbol
1: "hola" y
           ^


In [16]:
""hola" y "adios"" # Error

ERROR: Error in parse(text = x, srcfile = src): <text>:1:3: unexpected symbol
1: ""hola
      ^


In [17]:
'"hola" y "adios"' # Para este tipo de cosas se usan las comillas simples

[1] "\"hola\" y \"adios\""

In [18]:
1 / 0

[1] Inf

In [19]:
1 / Inf

[1] 0

In [20]:
0 / 0

[1] NaN

In [21]:
NULL

NULL

In [22]:
?NULL

NULL                   package:base                    R Documentation

_T_h_e _N_u_l_l _O_b_j_e_c_t

_D_e_s_c_r_i_p_t_i_o_n:

     ‘NULL’ represents the null object in R: it is a reserved word.
     ‘NULL’ is often returned by expressions and functions whose value
     is undefined.

_U_s_a_g_e:

     NULL
     as.null(x, ...)
     is.null(x)
     
_A_r_g_u_m_e_n_t_s:

       x: an object to be tested or coerced.

     ...: ignored.

_D_e_t_a_i_l_s:

     ‘NULL’ can be indexed (see Extract) in just about any
     syntactically legal way: whether it makes sense or not, the result
     is always ‘NULL’.  Objects with value ‘NULL’ can be changed by
     replacement operators and will be coerced to the type of the
     right-hand side.

     ‘NULL’ is also used as the empty pairlist: see the examples.
     Because pairlists are often promoted to lists, you may encounter
     ‘NULL’ being promoted to an empty list.

     Objects with value ‘NULL’ cannot have attributes as there is only
     one null object: attempts to assign them are either an error
     (‘attr’) or promote the object to an empty list with attribute(s)
     (‘attributes’ and ‘structure’).

_V_a_l_u_e:

     ‘as.null’ ignores its argument and returns ‘NULL’.

     ‘is.null’ returns ‘TRUE’ if its argument's value is ‘NULL’ and
     ‘FALSE’ otherwise.

_N_o_t_e:

     ‘is.null’ is a primitive function.

_R_e_f_e_r_e_n_c_e_s:

     Becker, R. A., Chambers, J. M. and Wilks, A. R. (1988) _The New S
     Language_.  Wadsworth & Brooks/Cole.

_E_x_a_m_p_l_e_s:

     is.null(list())     # FALSE (on purpose!)
     is.null(pairlist()) # TRUE
     is.null(integer(0)) # FALSE
     is.null(logical(0)) # FALSE
     as.null(list(a = 1, b = "c"))

In [23]:
NA

[1] NA

In [24]:
# ?NA

NA                    package:base                     R Documentation

'_N_o_t _A_v_a_i_l_a_b_l_e' / _M_i_s_s_i_n_g _V_a_l_u_e_s

_D_e_s_c_r_i_p_t_i_o_n:

     ‘NA’ is a logical constant of length 1 which contains a missing
     value indicator.  ‘NA’ can be coerced to any other vector type
     except raw.  There are also constants ‘NA_integer_’, ‘NA_real_’,
     ‘NA_complex_’ and ‘NA_character_’ of the other atomic vector types
     which support missing values: all of these are reserved words in
     the R language.

     The generic function ‘is.na’ indicates which elements are missing.

     The generic function ‘is.na<-’ sets elements to ‘NA’.

     The generic function ‘anyNA’ implements ‘any(is.na(x))’ in a
     possibly faster way (especially for atomic vectors).

_U_s_a_g_e:

     NA
     is.na(x)
     anyNA(x, recursive = FALSE)
     
     ## S3 method for class 'data.frame'
     is.na(x)
     
     is.na(x) <- value
     
_A_r_g_u_m_e_n_t_s:

       x: an R object to be tested: the default method for ‘is.na’ and
          ‘anyNA’ handle atomic vectors, lists, pairlists, and ‘NULL’.

recursive: logical: should ‘anyNA’ be applied recursively to lists and
          pairlists?

   value: a suitable index vector for use with ‘x’.

_D_e_t_a_i_l_s:

     The ‘NA’ of character type is distinct from the string ‘"NA"’.
     Programmers who need to specify an explicit missing string should
     use ‘NA_character_’ (rather than ‘"NA"’) or set elements to ‘NA’
     using ‘is.na<-’.

     ‘is.na’ and ‘anyNA’ are generic: you can write methods to handle
     specific classes of objects, see InternalMethods.

     Function ‘is.na<-’ may provide a safer way to set missingness.  It
     behaves differently for factors, for example.

     Numerical computations using ‘NA’ will normally result in ‘NA’: a
     possible exception is where ‘NaN’ is also involved, in which case
     either might result (which may depend on the R platform).
     However, this is not guaranteed and future CPUs and/or compilers
     may behave differently. Dynamic binary translation may also impact
     this behavior (with valgrind, computations using ‘NA’ may result
     in ‘NaN’ even when no ‘NaN’ is involved).

     Logical computations treat ‘NA’ as a missing ‘TRUE/FALSE’ value,
     and so may return ‘TRUE’ or ‘FALSE’ if the expression does not
     depend on the ‘NA’ operand.

     The default method for ‘anyNA’ handles atomic vectors without a
     class and ‘NULL’.  It calls ‘any(is.na(x))’ on objects with
     classes and for ‘recursive = FALSE’, on lists and pairlists.

_V_a_l_u_e:

     The default method for ‘is.na’ applied to an atomic vector returns
     a logical vector of the same length as its argument ‘x’,
     containing ‘TRUE’ for those elements marked ‘NA’ or, for numeric
     or complex vectors, ‘NaN’, and ‘FALSE’ otherwise. (A complex value
     is regarded as ‘NA’ if either its real or imaginary part is ‘NA’
     or ‘NaN’.)  ‘dim’, ‘dimnames’ and ‘names’ attributes are copied to
     the result.

     The default methods also work for lists and pairlists:
     For ‘is.na’, elementwise the result is false unless that element
     is a length-one atomic vector and the single element of that
     vector is regarded as ‘NA’ or ‘NaN’ (note that any ‘is.na’ method
     for the class of the element is ignored).
     ‘anyNA(recursive = FALSE)’ works the same way as ‘is.na’;
     ‘anyNA(recursive = TRUE)’ applies ‘anyNA’ (with method dispatch)
     to each element.

     The data frame method for ‘is.na’ returns a logical matrix with
     the same dimensions as the data frame, and with dimnames taken
     from the row and column names of the data frame.

     ‘anyNA(NULL)’ is false; ‘is.na(NULL)’ is ‘logical(0)’ (no longer
     warning since R version 3.5.0).

_R_e_f_e_r_e_n_c_e_s:

     Becker, R. A., Chambers, J. M. and Wilks, A. R. (1988) _The New S
     Language_.  Wa

# Operadores aritméticos

In [25]:
1 + 5

[1] 6

In [26]:
5 - 4

[1] 1

In [27]:
3 * 2.1

[1] 6.3

In [28]:
7 / (-4.3)

[1] -1.627907

In [53]:
2 ^ 3

[1] 8

In [30]:
2 ** (-1/2) # Igual que ^

[1] 0.7071068

In [31]:
4 %% 3

[1] 1

In [32]:
3 %/% 2

[1] 1

# Operadores lógicos

In [34]:
1 < 9.5

[1] TRUE

In [35]:
2.7 <= -5.3

[1] FALSE

In [36]:
4.9 > 2

[1] TRUE

In [37]:
4.9 >= 3

[1] TRUE

In [38]:
5 == 5

[1] TRUE

In [39]:
5 != 5

[1] FALSE

In [40]:
!(5 == 5)

[1] FALSE

In [41]:
(5 == 5) | (5 != 5)

[1] TRUE

In [42]:
(5 == 5) & (5 != 5)

[1] FALSE

In [43]:
1 == TRUE

[1] TRUE

In [44]:
0 == FALSE

[1] TRUE

In [51]:
7 == TRUE

[1] FALSE


In [192]:
as.logical(7) # WTF?

[1] TRUE

# Vectores
La funcion `c()` se usa para crear vectores

In [54]:
c(1,5,8)

[1] 1 5 8

In [49]:
print(c(1,5,8))

[1] 1 5 8


In [50]:
class(c(1,5,8))

[1] "numeric"

In [55]:
print(c(-1,5.5,8))

[1] -1.0  5.5  8.0


In [56]:
print(c(1.5,5,-8.5,5i))

[1]  1.5+0i  5.0+0i -8.5+0i  0.0+5i


In [57]:
class(c(1.5,5,-8.5,5i))

[1] "complex"

In [58]:
print(c("hola", "adios"))

[1] "hola"  "adios"


In [59]:
print(c("hola", 7))

[1] "hola" "7"   


In [60]:
print(c(TRUE, FALSE, TRUE))

[1]  TRUE FALSE  TRUE


In [61]:
print(c(T, F, T)) # Ojo cuidado!

[1]  TRUE FALSE  TRUE


In [62]:
print(c(TRUE, 0, TRUE))

[1] 1 0 1


In [63]:
print(as.logical(c(TRUE, 0, TRUE)))

[1]  TRUE FALSE  TRUE


In [64]:
print(as.character(c(3,4,5)))

[1] "3" "4" "5"


In [65]:
is.character(as.character(c(3,4,5)))

[1] TRUE

In [66]:
is.character(c(3,4,5))

[1] FALSE

Se pueden crear vectores dando un rango de valores usando `:`

In [67]:
print(1:4)

[1] 1 2 3 4


In [68]:
print(4:1)

[1] 4 3 2 1


In [69]:
print(1.1:6.9)

[1] 1.1 2.1 3.1 4.1 5.1 6.1


In [70]:
print(-1:5)

[1] -1  0  1  2  3  4  5


In [71]:
print(vector("numeric", length = 10))

 [1] 0 0 0 0 0 0 0 0 0 0


In [72]:
print(vector("logical", length = 10))

 [1] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE


<i>Atención que se vienen curvas...</i>

In [73]:
print(1:3 + 4:6)

[1] 5 7 9


In [74]:
print(1:3 + 4:7) # Warning! Recycling Rule

Warning message in 1:3 + 4:7:
“longitud de objeto mayor no es múltiplo de la longitud de uno menor”


[1] 5 7 9 8


In [75]:
print(1:3 * 4:6)

[1]  4 10 18


In [76]:
print(1:3 - 4:6)

[1] -3 -3 -3


In [77]:
print(1:3 / 4:6)

[1] 0.25 0.40 0.50


In [78]:
1:3 == 4:6

[1] FALSE FALSE FALSE

In [79]:
1:3 != 4:6

[1] TRUE TRUE TRUE

In [80]:
1:3 < 4:6

[1] TRUE TRUE TRUE

In [81]:
1:3 >= 4:6

[1] FALSE FALSE FALSE

In [82]:
!(0:3)

[1]  TRUE FALSE FALSE FALSE

### WTF? (Falling into the Floating Point Trap)
The R Inferno. Patrick Burns. https://www.burns-stat.com/pages/Tutor/R_inferno.pdf

In [83]:
.1 == (.3 / 3)

[1] FALSE

In [84]:
unique(c(.3, .4 - .1, .5 - .2, .6 - .3, .7 - .4))

[1] 0.3 0.3 0.3

<i>R is good enough at hiding numerical error that it is easy to forget that it is there. Don’t forget...</i>

In [85]:
1:5-1

[1] 0 1 2 3 4

In [86]:
1:(5-1)

[1] 1 2 3 4

In [87]:
10^2:6

[1] 100  99  98  97  96  95  94  93  92  91  90  89  88  87  86  85  84  83  82
[20]  81  80  79  78  77  76  75  74  73  72  71  70  69  68  67  66  65  64  63
[39]  62  61  60  59  58  57  56  55  54  53  52  51  50  49  48  47  46  45  44
[58]  43  42  41  40  39  38  37  36  35  34  33  32  31  30  29  28  27  26  25
[77]  24  23  22  21  20  19  18  17  16  15  14  13  12  11  10   9   8   7   6

In [88]:
?Syntax

Syntax                  package:base                   R Documentation

_O_p_e_r_a_t_o_r _S_y_n_t_a_x _a_n_d _P_r_e_c_e_d_e_n_c_e

_D_e_s_c_r_i_p_t_i_o_n:

     Outlines R syntax and gives the precedence of operators.

_D_e_t_a_i_l_s:

     The following unary and binary operators are defined.  They are
     listed in precedence groups, from highest to lowest.

       ‘:: :::’           access variables in a namespace              
       ‘$ @’              component / slot extraction                  
       ‘[ [[’             indexing                                     
       ‘^’                exponentiation (right to left)               
       ‘- +’              unary minus and plus                         
       ‘:’                sequence operator                            
       ‘%any% |>’         special operators (including ‘%%’ and ‘%/%’) 
       ‘* /’              multiply, divide                             
       ‘+ -’              (binary) add, subtract                       
       ‘< > <= >= == !=’  ordering and comparison                      
       ‘!’                negation                                     
       ‘&  &&’            and                                          
       ‘| ||’             or                                           
       ‘~’                as in formulae                               
       ‘-> ->>’           rightwards assignment                        
       ‘<- <<-’           assignment (right to left)                   
       ‘=’                assignment (right to left)                   
       ‘?’                help (unary and binary)                      
      
     Within an expression operators of equal precedence are evaluated
     from left to right except where indicated.  (Note that ‘=’ is not
     necessarily an operator.)

     The binary operators ‘::’, ‘:::’, ‘$’ and ‘@’ require names or
     string constants on the right hand side, and the first two also
     require them on the left.

     The links in the *See Also* section cover most other aspects of
     the basic syntax.

_N_o_t_e:

     There are substantial precedence differences between R and S.  In
     particular, in S ‘?’ has the same precedence as (binary) ‘+ -’ and
     ‘& && | ||’ have equal precedence.

_R_e_f_e_r_e_n_c_e_s:

     Becker, R. A., Chambers, J. M. and Wilks, A. R. (1988) _The New S
     Language_.  Wadsworth & Brooks/Cole.

_S_e_e _A_l_s_o:

     ‘Arithmetic’, ‘Comparison’, ‘Control’, ‘Extract’, ‘Logic’,
     ‘NumericConstants’, ‘Paren’, ‘Quotes’, ‘Reserved’.

     The ‘R Language Definition’ manual.

_E_x_a_m_p_l_e_s:

     ## Logical AND ("&&") has higher precedence than OR ("||"):
     TRUE || TRUE && FALSE   # is the same as
     TRUE || (TRUE && FALSE) # and different from
     (TRUE || TRUE) && FALSE
     
     ## Special operators have higher precedence than "!" (logical NOT).
     ## You can use this for %in% :
     ! 1:10 %in% c(2, 3, 5, 7) # same as !(1:10 %in% c(2, 3, 5, 7))
     ## but we strongly advise to use the "!( ... )" form in this case!
     
     
     ## '=' has lower precedence than '<-' ... so you should not mix them
     ##     (and '<-' is considered better style anyway):
     ## Consequently, this gives a ("non-catchable") error
      x <- y = 5  #->  Error in (x <- y) = 5 : ....

<i>Paréntesis... usad paréntesis...</i>

# Variables

In [89]:
x <- 1 # A la variable x le asigno 1

In [90]:
print(x)

[1] 1


In [91]:
x = 5 # A la variable x le asigno 1 

In [92]:
print(x)

[1] 5


<b>Atención:</b> `<-` no es lo mismo que `=`

In [95]:
# Do not run!
foo(93, a = 47)
foo(93, a <- 47)

ERROR: Error in foo(93, a = 47): no se pudo encontrar la función "foo"


In [96]:
# Do not run!
system.time(result <- foo(100))

   user  system elapsed 
      0       0       0 

Seguimos...

In [99]:
v <- c(2,6,8,10,-2,4.3)
print(v)

[1]  2.0  6.0  8.0 10.0 -2.0  4.3


In [100]:
print(v + 1) # Recycling Rule

[1]  3.0  7.0  9.0 11.0 -1.0  5.3


In [101]:
print(v * v)

[1]   4.00  36.00  64.00 100.00   4.00  18.49


In [102]:
print(v == v)

[1] TRUE TRUE TRUE TRUE TRUE TRUE


In [103]:
all(v == v)

[1] TRUE

In [104]:
identical(v,v)

[1] TRUE

In [105]:
print(c(3,2) %in% v)

[1] FALSE  TRUE


In [106]:
intersect(c(3,2), v)

[1] 2

In [107]:
print(union(c(3,2), v))

[1]  3.0  2.0  6.0  8.0 10.0 -2.0  4.3


In [108]:
print(union(v, c(3,2)))

[1]  2.0  6.0  8.0 10.0 -2.0  4.3  3.0


In [109]:
print(setdiff(c(3,2), v))

[1] 3


In [110]:
print(setdiff(v, c(3,2)))

[1]  6.0  8.0 10.0 -2.0  4.3


In [111]:
print(setdiff(abs(v), c(3,2)))

[1]  6.0  8.0 10.0  4.3


In [112]:
any(v > 2)

[1] TRUE

In [113]:
all(v > 2)

[1] FALSE

# Más sobre vectores

In [114]:
print(v)

[1]  2.0  6.0  8.0 10.0 -2.0  4.3


In [115]:
v[1]

[1] 2

In [116]:
v[0] # Nada

numeric(0)

In [117]:
print(v[-1])

[1]  6.0  8.0 10.0 -2.0  4.3


In [118]:
print(v[-1:-2])

[1]  8.0 10.0 -2.0  4.3


In [119]:
v

[1]  2.0  6.0  8.0 10.0 -2.0  4.3

In [120]:
length(v)

[1] 6

In [121]:
length(4)

[1] 1

In [122]:
length("hola")

[1] 1

In [123]:
nchar("hola") # Más sobre cadenas de caracteres más adelante...

[1] 4

In [124]:
v >= 0

[1]  TRUE  TRUE  TRUE  TRUE FALSE  TRUE

In [125]:
print(v[v >= 0])

[1]  2.0  6.0  8.0 10.0  4.3


In [126]:
print(v[v < 0])

[1] -2


In [127]:
print(v[v >= 0 & v <= 5])

[1] 2.0 4.3


In [128]:
v[c(TRUE,FALSE)]

[1]  2  8 -2

In [129]:
v[c(-1,-4)]

[1]  6.0  8.0 -2.0  4.3

In [130]:
sum(v)

[1] 28.3

In [131]:
prod(v)

[1] -8256

In [132]:
min(v)

[1] -2

In [133]:
max(v)

[1] 10

In [135]:
w <- c(NULL, 3, NA, 7, NaN)
print(w)

[1]   3  NA   7 NaN


In [136]:
length(w)

[1] 4

In [137]:
class(w)

[1] "numeric"

In [138]:
sum(w)

[1] NA

In [139]:
sum(w, na.rm = TRUE)

[1] 10

In [140]:
prod(w)

[1] NA

In [141]:
prod(w, na.rm = TRUE)

[1] 21

In [142]:
min(w)

[1] NA

In [143]:
min(w, na.rm = TRUE)

[1] 3

In [144]:
max(w)

[1] NA

In [145]:
max(w, na.rm = TRUE)

[1] 7

Se pueden crear vectores tambien con `seq` o con `rep`

In [146]:
seq(12, 30, 3) # seq(from=12, to=30, by=3)

[1] 12 15 18 21 24 27 30

In [147]:
seq(-12, 30, 3.4)

[1] -12.0  -8.6  -5.2  -1.8   1.6   5.0   8.4  11.8  15.2  18.6  22.0  25.4
[13]  28.8

In [148]:
print(seq(-12, 30, 3.4))

 [1] -12.0  -8.6  -5.2  -1.8   1.6   5.0   8.4  11.8  15.2  18.6  22.0  25.4
[13]  28.8


In [149]:
seq(1.1, 7, 10)

[1] 1.1

In [150]:
seq(1.1, 7, length=10)

[1] 1.100000 1.755556 2.411111 3.066667 3.722222 4.377778 5.033333 5.688889
 [9] 6.344444 7.000000

In [151]:
?seq

seq                    package:base                    R Documentation

_S_e_q_u_e_n_c_e _G_e_n_e_r_a_t_i_o_n

_D_e_s_c_r_i_p_t_i_o_n:

     Generate regular sequences.  ‘seq’ is a standard generic with a
     default method.  ‘seq.int’ is a primitive which can be much faster
     but has a few restrictions.  ‘seq_along’ and ‘seq_len’ are very
     fast primitives for two common cases.

_U_s_a_g_e:

     seq(...)
     
     ## Default S3 method:
     seq(from = 1, to = 1, by = ((to - from)/(length.out - 1)),
         length.out = NULL, along.with = NULL, ...)
     
     seq.int(from, to, by, length.out, along.with, ...)
     
     seq_along(along.with)
     seq_len(length.out)
     
_A_r_g_u_m_e_n_t_s:

     ...: arguments passed to or from methods.

from, to: the starting and (maximal) end values of the sequence.  Of
          length ‘1’ unless just ‘from’ is supplied as an unnamed
          argument.

      by: number: increment of the sequence.

length.out: desired length of the sequence.  A non-negative number,
          which for ‘seq’ and ‘seq.int’ will be rounded up if
          fractional.

along.with: take the length from the length of this argument.

_D_e_t_a_i_l_s:

     Numerical inputs should all be finite (that is, not infinite,
     ‘NaN’ or ‘NA’).

     The interpretation of the unnamed arguments of ‘seq’ and ‘seq.int’
     is _not_ standard, and it is recommended always to name the
     arguments when programming.

     ‘seq’ is generic, and only the default method is described here.
     Note that it dispatches on the class of the *first* argument
     irrespective of argument names.  This can have unintended
     consequences if it is called with just one argument intending this
     to be taken as ‘along.with’: it is much better to use ‘seq_along’
     in that case.

     ‘seq.int’ is an internal generic which dispatches on methods for
     ‘"seq"’ based on the class of the first supplied argument (before
     argument matching).

     Typical usages are

     seq(from, to)
     seq(from, to, by= )
     seq(from, to, length.out= )
     seq(along.with= )
     seq(from)
     seq(length.out= )
     
     The first form generates the sequence ‘from, from+/-1, ..., to’
     (identical to ‘from:to’).

     The second form generates ‘from, from+by’, ..., up to the sequence
     value less than or equal to ‘to’.  Specifying ‘to - from’ and ‘by’
     of opposite signs is an error.  Note that the computed final value
     can go just beyond ‘to’ to allow for rounding error, but is
     truncated to ‘to’.  (‘Just beyond’ is by up to 1e-10 times
     ‘abs(from - to)’.)

     The third generates a sequence of ‘length.out’ equally spaced
     values from ‘from’ to ‘to’.  (‘length.out’ is usually abbreviated
     to ‘length’ or ‘len’, and ‘seq_len’ is much faster.)

     The fourth form generates the integer sequence ‘1, 2, ...,
     length(along.with)’.  (‘along.with’ is usually abbreviated to
     ‘along’, and ‘seq_along’ is much faster.)

     The fifth form generates the sequence ‘1, 2, ..., length(from)’
     (as if argument ‘along.with’ had been specified), _unless_ the
     argument is numeric of length 1 when it is interpreted as ‘1:from’
     (even for ‘seq(0)’ for compatibility with S).  Using either
     ‘seq_along’ or ‘seq_len’ is much preferred (unless strict S
     compatibility is essential).

     The final form generates the integer sequence ‘1, 2, ...,
     length.out’ unless ‘length.out = 0’, when it generates
     ‘integer(0)’.

     Very small sequences (with ‘from - to’ of the order of 10^{-14}
     times the larger of the ends) will return ‘from’.

     For ‘seq’ (only), up to two of ‘from’, ‘to’ and ‘by’ can be
     supplied as complex values provided ‘length.out’ or ‘along.with’
     is specified.  More generally, the default method of ‘seq’ will
     handle classed objects with methods for the ‘Math’, ‘Ops’ and
     ‘Summary’ group generics.

    

In [152]:
seq()

[1] 1

In [153]:
rep(8,4)

[1] 8 8 8 8

In [154]:
rep(8,4.1) # Redondeo

[1] 8 8 8 8

In [155]:
print(rep("a",4))

[1] "a" "a" "a" "a"


In [156]:
rep(1:3, 5)

[1] 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3

In [157]:
length(rep(1:3, 5))

[1] 15

In [158]:
?rep

rep                    package:base                    R Documentation

_R_e_p_l_i_c_a_t_e _E_l_e_m_e_n_t_s _o_f _V_e_c_t_o_r_s _a_n_d _L_i_s_t_s

_D_e_s_c_r_i_p_t_i_o_n:

     ‘rep’ replicates the values in ‘x’.  It is a generic function, and
     the (internal) default method is described here.

     ‘rep.int’ and ‘rep_len’ are faster simplified versions for two
     common cases.  Internally, they are generic, so methods can be
     defined for them (see InternalMethods).

_U_s_a_g_e:

     rep(x, ...)
     
     rep.int(x, times)
     
     rep_len(x, length.out)
     
_A_r_g_u_m_e_n_t_s:

       x: a vector (of any mode including a ‘list’) or a factor or (for
          ‘rep’ only) a ‘POSIXct’ or ‘POSIXlt’ or ‘Date’ object; or an
          S4 object containing such an object.

     ...: further arguments to be passed to or from other methods.  For
          the internal default method these can include:

          ‘times’ an integer-valued vector giving the (non-negative)
              number of times to repeat each element if of length
              ‘length(x)’, or to repeat the whole vector if of length
              1.  Negative or ‘NA’ values are an error.  A ‘double’
              vector is accepted, other inputs being coerced to an
              integer or double vector.

          ‘length.out’ non-negative integer.  The desired length of the
              output vector.  Other inputs will be coerced to a double
              vector and the first element taken.  Ignored if ‘NA’ or
              invalid.

          ‘each’ non-negative integer.  Each element of ‘x’ is repeated
              ‘each’ times.  Other inputs will be coerced to an integer
              or double vector and the first element taken.  Treated as
              ‘1’ if ‘NA’ or invalid.

times, length.out: see ‘...’ above.

_D_e_t_a_i_l_s:

     The default behaviour is as if the call was

       rep(x, times = 1, length.out = NA, each = 1)
     
     .  Normally just one of the additional arguments is specified, but
     if ‘each’ is specified with either of the other two, its
     replication is performed first, and then that implied by ‘times’
     or ‘length.out’.

     If ‘times’ consists of a single integer, the result consists of
     the whole input repeated this many times.  If ‘times’ is a vector
     of the same length as ‘x’ (after replication by ‘each’), the
     result consists of ‘x[1]’ repeated ‘times[1]’ times, ‘x[2]’
     repeated ‘times[2]’ times and so on.

     ‘length.out’ may be given in place of ‘times’, in which case ‘x’
     is repeated as many times as is necessary to create a vector of
     this length.  If both are given, ‘length.out’ takes priority and
     ‘times’ is ignored.

     Non-integer values of ‘times’ will be truncated towards zero.  If
     ‘times’ is a computed quantity it is prudent to add a small fuzz
     or use ‘round’.  And analogously for ‘each’.

     If ‘x’ has length zero and ‘length.out’ is supplied and is
     positive, the values are filled in using the extraction rules,
     that is by an ‘NA’ of the appropriate class for an atomic vector
     (‘0’ for raw vectors) and ‘NULL’ for a list.

_V_a_l_u_e:

     An object of the same type as ‘x’.

     ‘rep.int’ and ‘rep_len’ return no attributes (except the class if
     returning a factor).

     The default method of ‘rep’ gives the result names (which will
     almost always contain duplicates) if ‘x’ had names, but retains no
     other attributes.

_N_o_t_e:

     Function ‘rep.int’ is a simple case which was provided as a
     separate function partly for S compatibility and partly for speed
     (especially when names can be dropped).  The performance of ‘rep’
     has been improved since, but ‘rep.int’ is still at least twice as
     fast when ‘x’ has names.

     The name ‘rep.int’ long precedes making ‘rep’ generic.

     Function ‘rep’ is a primitive, but (partial) 

In [159]:
rep(c(5,12,13), 2)

[1]  5 12 13  5 12 13

In [160]:
rep(c(5,12,13), each=2)

[1]  5  5 12 12 13 13

In [161]:
letters

[1] "a" "b" "c" "d" "e" "f" "g" "h" "i" "j" "k" "l" "m" "n" "o" "p" "q" "r" "s"
[20] "t" "u" "v" "w" "x" "y" "z"

In [162]:
LETTERS

[1] "A" "B" "C" "D" "E" "F" "G" "H" "I" "J" "K" "L" "M" "N" "O" "P" "Q" "R" "S"
[20] "T" "U" "V" "W" "X" "Y" "Z"

In [163]:
month.abb

[1] "Jan" "Feb" "Mar" "Apr" "May" "Jun" "Jul" "Aug" "Sep" "Oct" "Nov" "Dec"

In [164]:
month.name

[1] "January"   "February"  "March"     "April"     "May"       "June"     
 [7] "July"      "August"    "September" "October"   "November"  "December"

### WTF?

In [165]:
x == NA

[1] NA

In [166]:
x

[1] 5

In [167]:
class(x == NA)

[1] "logical"

In [168]:
NA == NA

[1] NA

In [169]:
3 == c(3, 1, 3, NA)

[1]  TRUE FALSE  TRUE    NA

In [170]:
is.na(x)

[1] FALSE

In [171]:
is.na(c(3, 1, 3, NA))

[1] FALSE FALSE FALSE  TRUE

In [172]:
xnull <- NULL
xnull == NULL

logical(0)

In [173]:
xnotnull <- 42
xnotnull == NULL

logical(0)

In [174]:
is.null(xnull)

[1] TRUE

In [175]:
print(xnull == NULL)
print(xnotnull == NULL)

logical(0)
logical(0)


In [177]:
x1 <- 10:1
x1 == c(4, 6)

[1] FALSE FALSE FALSE FALSE FALSE FALSE  TRUE FALSE FALSE FALSE

In [178]:
x1 %in% c(4, 6)

[1] FALSE FALSE FALSE FALSE  TRUE FALSE  TRUE FALSE FALSE FALSE

In [180]:
x1 == 4

[1] FALSE FALSE FALSE FALSE FALSE FALSE  TRUE FALSE FALSE FALSE

In [183]:
x1 == 4 | 6

[1] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE

In [191]:
as.logical(6)

[1] TRUE

In [184]:
as.logical(6) & 0

[1] FALSE

In [185]:
x1 == (4 | 6)

[1] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE  TRUE

In [186]:
x1 == 4 | x1 == 6

[1] FALSE FALSE FALSE FALSE  TRUE FALSE  TRUE FALSE FALSE FALSE

<i>Esos paréntesis... ¡que no falten!</i>

In [193]:
50 < "7"

[1] TRUE

In [194]:
"50" < "7"

[1] TRUE

In [195]:
length(x != 1)

[1] 1

In [196]:
length(x) != 1

[1] FALSE

<i>No dejéis que R decida por vosotr@s...</i>

In [197]:
xna <- c(1, NA, 3, 2, 4, 2)
xna[xna == 2]

[1] NA  2  2

In [198]:
!is.na(xna)

[1]  TRUE FALSE  TRUE  TRUE  TRUE  TRUE

In [199]:
xna == 2

[1] FALSE    NA FALSE  TRUE FALSE  TRUE

In [200]:
xna[xna == 2 & !is.na(xna)] # Analizar!

[1] 2 2

In [201]:
which(xna == 2)

[1] 4 6

In [202]:
xna[which(xna == 2)]

[1] 2 2

In [203]:
x4 <- c(a=1, b=2, a=3)
print(x4)

a b a 
1 2 3 


In [204]:
x4["a"]

a 
1

In [205]:
names(x4)

[1] "a" "b" "a"

In [206]:
x4[names(x4) %in% "a"]

a a 
1 3

In [207]:
print(c("missing value"=NA, "real string"="NA"))

missing value   real string 
           NA          "NA" 


### Ejercicios vectores
1) Crea un vector de números impares entre el 1 y el 30 (ambos inclusive)
2) Crea los siguientes vectores:
    * un vector del 1 al 20
    * un vector del 20 al 1
    * un vector que tenga el siguiente patrón 1,2,3,...,19,20,19,18,...,2,1
3) Crea una secuencia de números del 1 al 30 con un incremento de 0.5
4) Crea una secuencia que contenga las cuatro primeras letras del abecedario en minúscula 3 veces cada una (a a a b b b c c c d d d)
5) Crea el vector numérico `x` con los valores 2.3, 3.3, 4.3 y accede al segundo elemento del vector
6) Crea un vector numérico `z` que contenga los números del 1 al 10. Cambia la clase del vector forzando que sea de tipo carácter. Después cambia el vector `z` a numerico otra vez
7) Crea un vector numérico con valores no ordenados usando la función `sample()`. Una vez creado ordena el vector de forma ascendente usando la función `sort()`. ¿Si quisieras invertir el orden de los elementos del vector que función utilizarías?
8) Crea un vector `x` que contenga los elementos -5,-1,0,1,2,3,4,5,6. Escribe un código del tipo `x[algo]`, para extraer:
    * elementos de x menores que 0,
    * elementos de x menores o igual que 0,
    * elementos of x mayor o igual que 3,
    * elementos de x menor que 0 o mayor que 4,
    * elementos de x mayor que 0 y menor que 4,
    * elementos de x distintos de 0
9) Crea los siguientes vectores `x<-month.name[1:6]` y `z<-month.name[4:10]` a partir del vector original `month.name`. Recupera los valores idénticos entre los vectores x y z usando `%in%`
10) R permite extraer elementos de un vector que satisfacen determinadas condiciones usando la función `subset()`. Para el vector x <- c(6,1:3,NA,12) calcula los elementos mayores que 5 en x usando:
     * el filtrado normal, es decir, con el operador `>`
     * la función `subset()`

# Listas

Son estructuras de datos que permiten combinar elementos de diferente tipo y/o tamaño.

In [208]:
list_data <- list("Red", "Green", c(21,32,11), TRUE, 51.23, 119.1i)
print(list_data)

[[1]]
[1] "Red"

[[2]]
[1] "Green"

[[3]]
[1] 21 32 11

[[4]]
[1] TRUE

[[5]]
[1] 51.23

[[6]]
[1] 0+119.1i



In [209]:
class(list_data)

[1] "list"

In [212]:
print(list_data[5:6])

[[1]]
[1] 51.23

[[2]]
[1] 0+119.1i



In [217]:
print(list_data[6])

[[1]]
[1] 0+119.1i



In [214]:
class(list_data[6])

[1] "list"

In [216]:
print(list_data[[6]])

[1] 0+119.1i


In [215]:
class(list_data[[6]])

[1] "complex"

In [218]:
names(list_data) <- c("Colors", "Age", "Time")
print(list_data)

$Colors
[1] "Red"

$Age
[1] "Green"

$Time
[1] 21 32 11

$<NA>
[1] TRUE

$<NA>
[1] 51.23

$<NA>
[1] 0+119.1i



In [219]:
names(list_data) <- c("A", "B", "C", "E", "F", "A")
print(list_data)

$A
[1] "Red"

$B
[1] "Green"

$C
[1] 21 32 11

$E
[1] TRUE

$F
[1] 51.23

$A
[1] 0+119.1i



In [223]:
attributes(list_data)

$names
[1] "A" "B" "C" "E" "F" "A"

In [224]:
list_data[[1]]

[1] "Red"

In [226]:
list_data[["A"]]

[1] "Red"

In [229]:
list_data[[1]] <- 5

In [230]:
list_data[[1]]

[1] 5

In [231]:
print(list_data[1:3])

$A
[1] 5

$B
[1] "Green"

$C
[1] 21 32 11



In [232]:
print(list_data[c("A","E")])

$A
[1] 5

$E
[1] TRUE



In [233]:
print(unlist(list_data))

         A          B         C1         C2         C3          E          F 
       "5"    "Green"       "21"       "32"       "11"     "TRUE"    "51.23" 
         A 
"0+119.1i" 


In [234]:
class(unlist(list_data))

[1] "character"

In [235]:
num_list <- list(1,2,3,4,5)
day_list <- list("Mon","Tue","Wed", "Thurs", "Fri")
new_list <- c(num_list, day_list)
print(new_list)

[[1]]
[1] 1

[[2]]
[1] 2

[[3]]
[1] 3

[[4]]
[1] 4

[[5]]
[1] 5

[[6]]
[1] "Mon"

[[7]]
[1] "Tue"

[[8]]
[1] "Wed"

[[9]]
[1] "Thurs"

[[10]]
[1] "Fri"



In [236]:
new_list[[5]] <- NULL # Opcion 1
print(new_list)

[[1]]
[1] 1

[[2]]
[1] 2

[[3]]
[1] 3

[[4]]
[1] 4

[[5]]
[1] "Mon"

[[6]]
[1] "Tue"

[[7]]
[1] "Wed"

[[8]]
[1] "Thurs"

[[9]]
[1] "Fri"



In [237]:
print(new_list[-5]) # Opcion 2

[[1]]
[1] 1

[[2]]
[1] 2

[[3]]
[1] 3

[[4]]
[1] 4

[[5]]
[1] "Tue"

[[6]]
[1] "Wed"

[[7]]
[1] "Thurs"

[[8]]
[1] "Fri"



In [239]:
print(list(hola="Hola", 1, 3, adios = 5.6))

$hola
[1] "Hola"

[[2]]
[1] 1

[[3]]
[1] 3

$adios
[1] 5.6



### Ejercicios listas
1) Crea una lista llamada `mi_lista` que contenga los siguientes elementos: un vector numérico de 15 elementos, un vector de caracteres de 5 elementos y un vector de valores booleanos de 10 elementos todos TRUE
2) Dada la siguiente lista `my_list <- list(name="Fred", wife="Mary", no.children=3, child.ages=c(4,7,9))`:
    * Imprime los nombres de todos los componentes de la lista
    * Devuelve el segundo componente de la lista
    * Recupera el segundo elemento del cuarto componente de la lista 
    * Imprime la longitud del cuarto elemento de la lista
    * Reemplaza el cuarto elemento de la lista por un vector de 12 numeros del 1 al 12
    * Elimina el componente `wife`
    * Añade un componente más a la lista llamado `pepe`
3) Convertir un vector de 30 números postivos y negativos en una lista con [1ra componente: los 2 primeros elementos, 2da componente: los 5 siguientes pero como caracteres, 3ra componente: los elementos restantes que sean valores positivos, 4ta componente: una lista de caracteres con tu nombre y apellidos (ej: "Rocio" "Romero" "Zaliz")]
    * Una vez creado ponles nombre (ej: "1ro", "2do" etc)
    * Accede al tercer elemento por su nombre
    * Fusiona el primer y cuarto componente en un quito componente y borra los originales
4) Crea una nueva lista cuyos componentes sean las listas de los ejericios anteriores (OJO: Su longitude debería ser 3)
5) Crea una nueva lista que concatene las listas de los tres primeros ejericios. ¿Qué longitud tiene?

# Matrices

* Las matrices son vectores con un atributo de dimensión. El atributo de dimensión es en sí mismo un vector entero de longitud 2 (nrow, ncol).
* Todas las columnas de una matriz deben tener el mismo tipo (numérico, carácter, etc.) y la misma longitud.

In [240]:
x <- 1:20
dim(x) <- c(5,4)
print(x)

     [,1] [,2] [,3] [,4]
[1,]    1    6   11   16
[2,]    2    7   12   17
[3,]    3    8   13   18
[4,]    4    9   14   19
[5,]    5   10   15   20


In [242]:
x

[,1] [,2] [,3] [,4]
[1,] 1     6   11   16  
[2,] 2     7   12   17  
[3,] 3     8   13   18  
[4,] 4     9   14   19  
[5,] 5    10   15   20

In [241]:
class(x)

[1] "matrix" "array"

In [229]:
matrix(nrow = 2, ncol = 3)

[,1] [,2] [,3]
[1,] NA   NA   NA  
[2,] NA   NA   NA

In [248]:
matrix(0, nrow = 2, ncol = 3)

[,1] [,2] [,3]
[1,] 0    0    0   
[2,] 0    0    0

In [249]:
matrix("a", nrow = 2, ncol = 3)

[,1] [,2] [,3]
[1,] a    a    a   
[2,] a    a    a

In [250]:
matrix(1:10, nrow = 3, ncol = 4)

Warning message in matrix(1:10, nrow = 3, ncol = 4):
“la longitud de los datos [10] no es un submúltiplo o múltiplo del número de filas [3] en la matriz”


[,1] [,2] [,3] [,4]
[1,] 1    4    7    10  
[2,] 2    5    8     1  
[3,] 3    6    9     2

In [252]:
matrix(1:10, nrow=3, ncol = 4, byrow=TRUE)

Warning message in matrix(1:10, nrow = 3, ncol = 4, byrow = TRUE):
“la longitud de los datos [10] no es un submúltiplo o múltiplo del número de filas [3] en la matriz”


[,1] [,2] [,3] [,4]
[1,] 1     2   3    4   
[2,] 5     6   7    8   
[3,] 9    10   1    2

In [253]:
matrix(1:12, nrow = 3)

[,1] [,2] [,3] [,4]
[1,] 1    4    7    10  
[2,] 2    5    8    11  
[3,] 3    6    9    12

In [254]:
matrix(1:12, ncol=3)

[,1] [,2] [,3]
[1,] 1    5     9  
[2,] 2    6    10  
[3,] 3    7    11  
[4,] 4    8    12

In [256]:
m <- matrix(1.1:12.1, nrow=3, byrow=FALSE)
rownames(m) <- c("A","B","C")
colnames(m) <- c("1","2","x","y")
m

1   2   x   y   
A 1.1 4.1 7.1 10.1
B 2.1 5.1 8.1 11.1
C 3.1 6.1 9.1 12.1

In [258]:
print(dim(m))

[1] 3 4


In [259]:
length(m)

[1] 12

In [260]:
rbind(1:5,11:15)

[,1] [,2] [,3] [,4] [,5]
[1,]  1    2    3    4    5  
[2,] 11   12   13   14   15

In [261]:
cbind(1:5,11:15)

[,1] [,2]
[1,] 1    11  
[2,] 2    12  
[3,] 3    13  
[4,] 4    14  
[5,] 5    15

In [262]:
m

1   2   x   y   
A 1.1 4.1 7.1 10.1
B 2.1 5.1 8.1 11.1
C 3.1 6.1 9.1 12.1

In [263]:
m[1,1]

[1] 1.1

In [264]:
print(m[1,])

   1    2    x    y 
 1.1  4.1  7.1 10.1 


In [265]:
print(m[,1])

  A   B   C 
1.1 2.1 3.1 


In [266]:
m[1:2,1:3]

1   2   x  
A 1.1 4.1 7.1
B 2.1 5.1 8.1

In [267]:
m

1   2   x   y   
A 1.1 4.1 7.1 10.1
B 2.1 5.1 8.1 11.1
C 3.1 6.1 9.1 12.1

In [268]:
m[,c("1", "x")]

1   x  
A 1.1 7.1
B 2.1 8.1
C 3.1 9.1

In [269]:
m[,c(-1,-4)]

2   x  
A 4.1 7.1
B 5.1 8.1
C 6.1 9.1

In [270]:
m[,-"x"] # Error!

ERROR: Error in -"x": argumento no válido para un operador unitario


In [271]:
c("x") %in% colnames(m) 

[1] TRUE

In [272]:
colnames(m) %in% c("x")

[1] FALSE FALSE  TRUE FALSE

In [273]:
m <- m[,!colnames(m) %in% c("x")]
m

1   2   y   
A 1.1 4.1 10.1
B 2.1 5.1 11.1
C 3.1 6.1 12.1

In [274]:
class(m)

[1] "matrix" "array"

In [275]:
class(m[1,])

[1] "numeric"

In [276]:
m[1,,drop=FALSE]

1   2   y   
A 1.1 4.1 10.1

In [278]:
print(m[1,,drop=TRUE])

   1    2    y 
 1.1  4.1 10.1 


In [279]:
mx <- matrix(1:12, nrow=3, byrow=TRUE)
mx

[,1] [,2] [,3] [,4]
[1,] 1     2    3    4  
[2,] 5     6    7    8  
[3,] 9    10   11   12

In [280]:
mx[3, 2] <- 4
mx

[,1] [,2] [,3] [,4]
[1,] 1    2     3    4  
[2,] 5    6     7    8  
[3,] 9    4    11   12

In [281]:
mx[2, ] <- c(1,3) # Recycle!
mx

[,1] [,2] [,3] [,4]
[1,] 1    2     3    4  
[2,] 1    3     1    3  
[3,] 9    4    11   12

In [282]:
mx[1:2, 3:4] <- c(8,4,2,1)
mx

[,1] [,2] [,3] [,4]
[1,] 1    2     8    2  
[2,] 1    3     4    1  
[3,] 9    4    11   12

In [285]:
print(dim(mx))

[1] 3 4


In [287]:
dim(mx)[1]

[1] 3

In [288]:
dim(mx)[2]

[1] 4

In [283]:
ncol(mx)

[1] 4

In [284]:
nrow(mx)

[1] 3

In [289]:
t(mx)

[,1] [,2] [,3]
[1,] 1    1     9  
[2,] 2    3     4  
[3,] 8    4    11  
[4,] 2    1    12

In [290]:
diag(mx)

[1]  1  3 11

In [291]:
m

1   2   y   
A 1.1 4.1 10.1
B 2.1 5.1 11.1
C 3.1 6.1 12.1

In [271]:
m * m

1    2     y     
A 1.21 16.81 102.01
B 4.41 26.01 123.21
C 9.61 37.21 146.41

In [292]:
m %*% m

1     2      y     
A 41.13  87.03 178.83
B 47.43 102.33 212.13
C 53.73 117.63 245.43

In [293]:
a <- attributes(m)
a

$dim
[1] 3 3

$dimnames
$dimnames[[1]]
[1] "A" "B" "C"

$dimnames[[2]]
[1] "1" "2" "y"

In [294]:
a$dimnames[[1]]

[1] "A" "B" "C"

In [295]:
class(attributes(m))

[1] "list"

# Arrays

Las matrices con más de dos dimensiones se llaman `array`

In [296]:
x <- 1:20
dim(x) <- c(2,5,2)
print(x)

, , 1

     [,1] [,2] [,3] [,4] [,5]
[1,]    1    3    5    7    9
[2,]    2    4    6    8   10

, , 2

     [,1] [,2] [,3] [,4] [,5]
[1,]   11   13   15   17   19
[2,]   12   14   16   18   20



In [297]:
a <- array(1:24, dim=c(3,4,2))
print(a) # Una matriz de 3 dimensiones

, , 1

     [,1] [,2] [,3] [,4]
[1,]    1    4    7   10
[2,]    2    5    8   11
[3,]    3    6    9   12

, , 2

     [,1] [,2] [,3] [,4]
[1,]   13   16   19   22
[2,]   14   17   20   23
[3,]   15   18   21   24



In [302]:
a <- array(1:24, dim=c(3,4,2), 
           dimnames = list(c("ROW1","ROW2","ROW3"), 
                           c("COL1","COL2","COL3","COL4"), 
                           c("Matrix1","Matrix2")))
print(a)

, , Matrix1

     COL1 COL2 COL3 COL4
ROW1    1    4    7   10
ROW2    2    5    8   11
ROW3    3    6    9   12

, , Matrix2

     COL1 COL2 COL3 COL4
ROW1   13   16   19   22
ROW2   14   17   20   23
ROW3   15   18   21   24



In [303]:
a[1,3,]

Matrix1 Matrix2 
      7      19

In [304]:
a[1,3,1]

[1] 7

In [305]:
print(a[3,,2])

COL1 COL2 COL3 COL4 
  15   18   21   24 


In [306]:
print(a[,,2])

     COL1 COL2 COL3 COL4
ROW1   13   16   19   22
ROW2   14   17   20   23
ROW3   15   18   21   24


### Ejercicios matrices y arrays
1) Dada la siguiente matrix:
<pre>laberinto <- matrix(c(
   "O", "X", "O", "O", "O",
   "O", "X", "X", "X", "O",
   "O", "O", "O", "O", "X",
   "X", "X", "X", "O", "X",
   "O", "O", "O", "O", "O"
 ), nrow = 5, byrow = TRUE)</pre>
    * Indique donde están las "X" usando la función `which`
    * Indique donde están las "X" usando la función `which` pero usando el parámetro `arr.ind`
    * Indique cuantos valores "X" hay en la matriz
    * Reemplace las "X" por 1 y los "O" por 0 y convierta la matrix en una matrix numérica
    * Indique si la matrix es simétrica
    * Cree una nueva matrix con los valores en las filas y columnas pares 
2) Crea una matriz que represente un Sudoku. Debe estar inicializada en NA. Luego rellenar solo un 10% de las casillas con un valor entre 1 y 9 (HINT: usa la función `sample`). No se preocupe de que sea un esquema válido (se pueden repetir valores en una fila por ejemplo... eso ya lo haremos más adelante...)
3) Teniendo estas dos matrices:
<pre>matriz <- matrix(sample(1:9, 30,replace=TRUE), nrow=5)</pre>
<pre>mascara <- matrix(sample(c(TRUE,FALSE), 30, replace=TRUE), nrow=5)</pre>
    * Aplique la máscara a la matrix, en donde si la posicion en la máscara es FALSE entonces el resultado es 0 y sino se mantiene su valor
    * Calcule el producto de la matriz original por la matriz modificada traspuesta (NOTA: la matriz final será de 5x5)
4) Crea un array 5D llamado "mi_array5D" con las siguientes características, rellénalo con números enteros consecutivos comenzando desde 1:
    - Tamaño de la primera dimensión: 2 elementos
    - Tamaño de la segunda dimensión: 3 elementos
    - Tamaño de la tercera dimensión: 4 elementos
    - Tamaño de la cuarta dimensión: 5 elementos
    - Tamaño de la quinta dimensión: 6 elementos
    
    4.1) Accede a los siguientes elementos del array:
    * los elementos pares (analice la posición de esos valores en las 5 dimensiones)
    * estudiando el caso anterior muestre los elementos impares sin usar ningun tipo de condicional, igualdad o desigualdad
    
    4.2) Redimensiona el array para que tenga:
    - Tamaño de la primera dimensión: 6 elementos.
    - Tamaño de la segunda dimensión: 5 elementos.
    - Tamaño de la tercera dimensión: 4 elementos.
    - Tamaño de la cuarta dimensión: 3 elementos.
    - Tamaño de la quinta dimensión: 2 elementos.
5) Supongamos que tenemos un grafo no dirigido con 6 nodos etiquetados del 1 al 6, y las siguientes aristas:
    * Arista 1: (1, 2)
    * Arista 2: (1, 3)
    * Arista 3: (2, 4)
    * Arista 4: (2, 5)
    * Arista 5: (3, 6)
    * Arista 6: (4, 5)
    
    Crea una matriz de adyacencia "matriz_adyacencia" en R para representar este grafo. En una matriz de adyacencia, las filas y columnas representan los nodos, y un valor 1 indica que existe una arista entre los nodos correspondientes, mientras que un valor 0 indica la ausencia de una arista.
    * Calcula el grado del nodo 4 en el grafo. El grado de un nodo es la cantidad de aristas que inciden en él
    * Encuentra todos los nodos adyacentes del nodo 2
    * Cuenta la cantidad de nodos que tiene una arista hacia si mismos (self-loop)

# Factores (variables nominales)
Los factores son vectores para valores categóricos
* Levels: refers to the input values
* Labels: refers to the output values of the new factor

In [307]:
Pain <- c(0,3,2,2,1)
Pain

[1] 0 3 2 2 1

In [308]:
SevPain <- factor(c(0,3,2,2,1), levels=c(0,1,2,3), labels=c("none","mild","medium","severe"))
class(SevPain)

[1] "factor"

In [309]:
SevPain

[1] none   severe medium medium mild  
Levels: none mild medium severe

In [311]:
directions <- c("North", "East", "South", "South")
factor(directions)

[1] North East  South South
Levels: East North South

In [312]:
factor(directions, levels=c("North", "East", "South", "West"), labels=c("N","E","S","W"))

[1] N E S S
Levels: N E S W

In [314]:
table(factor(directions))


 East North South 
    1     1     2 

# Factores ordenados (variables ordinales)

In [315]:
status <- c("Lo", "Hi", "Med", "Med", "Hi")
ordered.status <- factor(status, levels=c("Lo", "Med", "Hi"), ordered=TRUE)
print(ordered.status)

[1] Lo  Hi  Med Med Hi 
Levels: Lo < Med < Hi


In [316]:
table(status)

status
 Hi  Lo Med 
  2   1   2 

In [317]:
table(ordered.status)

ordered.status
 Lo Med  Hi 
  1   2   2 

 ### WTF?

In [318]:
f <- factor(c(101,6,8,9,6,103))
is.numeric(f)

[1] FALSE

In [319]:
f

[1] 101 6   8   9   6   103
Levels: 6 8 9 101 103

In [320]:
as.numeric(f)

[1] 4 1 2 3 1 5

In [321]:
as.numeric(as.character(f))

[1] 101   6   8   9   6 103

In [322]:
as.numeric(levels(f))

[1]   6   8   9 101 103

In [324]:
ff <- factor(c("AA", "BA", "CA"))
ff

[1] AA BA CA
Levels: AA BA CA

In [325]:
ff[1:2]

[1] AA BA
Levels: AA BA CA

In [326]:
ff[1:2, drop=TRUE] # Opcion 1

[1] AA BA
Levels: AA BA

In [327]:
factor(ff[1:2]) # Opcion 2

[1] AA BA
Levels: AA BA

In [328]:
f1 <- factor(c("AA", "BA", NA, "NA"))
f1

[1] AA   BA   <NA> NA  
Levels: AA BA NA

In [329]:
f1 <- factor(c("AA", "BA", NA, "NA"), exclude=NULL)
f1

[1] AA   BA   <NA> NA  
Levels: AA BA NA <NA>

### Ejercicios factores
1) Crea un factor llamado "fact_puntuacion" que contenga puntuaciones de 1 al 5 para 1000 productos. Utiliza la función `summary()` para obtener un resumen de la distribución de puntuaciones. ¿Qué puedes deducir del tipo de aleatoriedad usada en `sample`? ¿Es normal, uniforme, ...?
2) Crea un factor ordenado para edades entre 0 y 100 de 100 personas. Utiliza la función `cut` para generar 3 nieveles separados. Ahora reetiqueta el factor como "joven", "adulto" o "anciano". Muestra la frecuencia de cada nivel.
3) Crea un factor para el siguiente vector teniendo en cuenta que los niveles posibles son todas las letras de la "A" a la "Z":
<pre>v <- c("A","I", "I", "J", "A", "Z", "X")</pre>
    * Modifica una de las "I" por una "F"
    * Agrega una nueva "A" en última posición
    * Indica las letras que aparecen en el factor ordenadas por su frecuencia, empezando con la menos frecuente

# Data Frames
Un marco de datos o data frame es una matriz generalizada, donde las diferentes columnas pueden tener diferentes tipos de datos (numérico, carácter, factor, etc.).

Por ejemplo, vectores y/o factores de la misma longitud que están relacionados "transversalmente", de forma que los datos en la misma
posición proceden de la misma unidad experimental (sujeto, animal, etc.).

In [330]:
S <- as.factor(c("F","M","M","F"))
Patients <- data.frame(age=c(31,32,40,50), sex=S)
Patients

age sex
1 31  F  
2 32  M  
3 40  M  
4 50  F

In [332]:
employee <- c("John Doe","Peter Gynn","Jolie Hope")
salary <- c(21000, 23400, 26800)
startdate <- as.Date(c("2010-11-1","2008-3-25","2007-3-14"))

employ.data <- data.frame(employee, salary, startdate)
employ.data

employee   salary startdate 
1 John Doe   21000  2010-11-01
2 Peter Gynn 23400  2008-03-25
3 Jolie Hope 26800  2007-03-14

In [333]:
str(employ.data)

'data.frame':	3 obs. of  3 variables:
 $ employee : chr  "John Doe" "Peter Gynn" "Jolie Hope"
 $ salary   : num  21000 23400 26800
 $ startdate: Date, format: "2010-11-01" "2008-03-25" ...


In [334]:
employ.data <- data.frame(employee, salary, startdate, stringsAsFactors=TRUE)
employ.data

employee   salary startdate 
1 John Doe   21000  2010-11-01
2 Peter Gynn 23400  2008-03-25
3 Jolie Hope 26800  2007-03-14

In [335]:
ncol(employ.data)

[1] 3

In [336]:
nrow(employ.data)

[1] 3

In [337]:
length(employ.data) # ¡Cuidado!

[1] 3

In [338]:
summary(employ.data)

       employee     salary        startdate         
 John Doe  :1   Min.   :21000   Min.   :2007-03-14  
 Jolie Hope:1   1st Qu.:22200   1st Qu.:2007-09-18  
 Peter Gynn:1   Median :23400   Median :2008-03-25  
                Mean   :23733   Mean   :2008-10-02  
                3rd Qu.:25100   3rd Qu.:2009-07-13  
                Max.   :26800   Max.   :2010-11-01  

In [339]:
employ.data[1,1]

[1] John Doe
Levels: John Doe Jolie Hope Peter Gynn

In [340]:
employ.data[1,]

employee salary startdate 
1 John Doe 21000  2010-11-01

In [341]:
employ.data[,1]

[1] John Doe   Peter Gynn Jolie Hope
Levels: John Doe Jolie Hope Peter Gynn

In [342]:
employ.data$employee

[1] John Doe   Peter Gynn Jolie Hope
Levels: John Doe Jolie Hope Peter Gynn

In [343]:
rbind(employ.data, c("John Doe", 50000, "1990-11-1"))

employee   salary startdate 
1 John Doe   21000  2010-11-01
2 Peter Gynn 23400  2008-03-25
3 Jolie Hope 26800  2007-03-14
4 John Doe   50000  1990-11-01

In [344]:
rbind(employ.data, c("Rocio Romero", 50000, "1990-11-1")) # Error

Warning message in `[<-.factor`(`*tmp*`, ri, value = "Rocio Romero"):
“invalid factor level, NA generated”


employee   salary startdate 
1 John Doe   21000  2010-11-01
2 Peter Gynn 23400  2008-03-25
3 Jolie Hope 26800  2007-03-14
4 NA         50000  1990-11-01

In [346]:
rbind(employ.data, c("John Doe", 50000)) # Error

Warning message in rbind(deparse.level, ...):
“number of columns of result, 3, is not a multiple of vector length 2 of arg 2”


ERROR: Error in charToDate(x): character string is not in a standard unambiguous format


In [347]:
# Crear los datos para el dataframe
year <- c(2000, 2020, 2021, 2021, 2022, 2022, 2023, 2023, 2024, 2024)
country <- c("Argentina", "Brasil", "Chile", "Colombia", "Ecuador", "Perú", "México", "Uruguay", "Paraguay", "Bolivia")
valor1 <- c(100, 120, 90, 110, 80, 105, 115, 95, 125, 75)

# Crear el dataframe
data1 <- data.frame(year, country, valor1)
data1

year country   valor1
1  2000 Argentina 100   
2  2020 Brasil    120   
3  2021 Chile      90   
4  2021 Colombia  110   
5  2022 Ecuador    80   
6  2022 Perú      105   
7  2023 México    115   
8  2023 Uruguay    95   
9  2024 Paraguay  125   
10 2024 Bolivia    75

In [348]:
# Crear los datos para el dataframe
country <- rep(c("Argentina", "Brasil", "Chile"), each = 1, times = 5)
year <- c(rep(seq(2000, 2006, by = 1), each = 2), 2020)
valor2 <- runif(15, min = 1, max = 100) # Valores aleatorios entre 1 y 100

# Crear el dataframe
data2 <- data.frame(country, year, valor2)
data2

country   year valor2  
1  Argentina 2000 91.65267
2  Brasil    2000 62.21677
3  Chile     2001 43.41373
4  Argentina 2001 54.66596
5  Brasil    2002  6.78937
6  Chile     2002 26.82483
7  Argentina 2003 40.31804
8  Brasil    2003 20.57673
9  Chile     2004 83.36083
10 Argentina 2004 16.13584
11 Brasil    2005 80.53844
12 Chile     2005 55.13579
13 Argentina 2006 66.56945
14 Brasil    2006 17.99815
15 Chile     2020 63.67248

In [349]:
?merge

merge                   package:base                   R Documentation

_M_e_r_g_e _T_w_o _D_a_t_a _F_r_a_m_e_s

_D_e_s_c_r_i_p_t_i_o_n:

     Merge two data frames by common columns or row names, or do other
     versions of database _join_ operations.

_U_s_a_g_e:

     merge(x, y, ...)
     
     ## Default S3 method:
     merge(x, y, ...)
     
     ## S3 method for class 'data.frame'
     merge(x, y, by = intersect(names(x), names(y)),
           by.x = by, by.y = by, all = FALSE, all.x = all, all.y = all,
           sort = TRUE, suffixes = c(".x",".y"), no.dups = TRUE,
           incomparables = NULL, ...)
     
_A_r_g_u_m_e_n_t_s:

    x, y: data frames, or objects to be coerced to one.

by, by.x, by.y: specifications of the columns used for merging.  See
          ‘Details’.

     all: logical; ‘all = L’ is shorthand for ‘all.x = L’ and ‘all.y =
          L’, where ‘L’ is either ‘TRUE’ or ‘FALSE’.

   all.x: logical; if ‘TRUE’, then extra rows will be added to the
          output, one for each row in ‘x’ that has no matching row in
          ‘y’.  These rows will have ‘NA’s in those columns that are
          usually filled with values from ‘y’.  The default is ‘FALSE’,
          so that only rows with data from both ‘x’ and ‘y’ are
          included in the output.

   all.y: logical; analogous to ‘all.x’.

    sort: logical.  Should the result be sorted on the ‘by’ columns?

suffixes: a character vector of length 2 specifying the suffixes to be
          used for making unique the names of columns in the result
          which are not used for merging (appearing in ‘by’ etc).

 no.dups: logical indicating that ‘suffixes’ are appended in more cases
          to avoid duplicated column names in the result.  This was
          implicitly false before R version 3.5.0.

incomparables: values which cannot be matched.  See ‘match’.  This is
          intended to be used for merging on one column, so these are
          incomparable values of that column.

     ...: arguments to be passed to or from methods.

_D_e_t_a_i_l_s:

     ‘merge’ is a generic function whose principal method is for data
     frames: the default method coerces its arguments to data frames
     and calls the ‘"data.frame"’ method.

     By default the data frames are merged on the columns with names
     they both have, but separate specifications of the columns can be
     given by ‘by.x’ and ‘by.y’.  The rows in the two data frames that
     match on the specified columns are extracted, and joined together.
     If there is more than one match, all possible matches contribute
     one row each.  For the precise meaning of ‘match’, see ‘match’.

     Columns to merge on can be specified by name, number or by a
     logical vector: the name ‘"row.names"’ or the number ‘0’ specifies
     the row names.  If specified by name it must correspond uniquely
     to a named column in the input.

     If ‘by’ or both ‘by.x’ and ‘by.y’ are of length 0 (a length zero
     vector or ‘NULL’), the result, ‘r’, is the _Cartesian product_ of
     ‘x’ and ‘y’, i.e., ‘dim(r) = c(nrow(x)*nrow(y), ncol(x) +
     ncol(y))’.

     If ‘all.x’ is true, all the non matching cases of ‘x’ are appended
     to the result as well, with ‘NA’ filled in the corresponding
     columns of ‘y’; analogously for ‘all.y’.

     If the columns in the data frames not used in merging have any
     common names, these have ‘suffixes’ (‘".x"’ and ‘".y"’ by default)
     appended to try to make the names of the result unique.  If this
     is not possible, an error is thrown.

     If a ‘by.x’ column name matches one of ‘y’, and if ‘no.dups’ is
     true (as by default), the y version gets suffixed as well,
     avoiding duplicate column names in the result.

     The complexity of the algorithm used is proportional to the length
     of the answer.

     In SQL database terminology, the default value of ‘all = FALSE’
     gives a _natural join_

In [350]:
merge(data1, data2, by = c("country", "year")) # conserva sólo las observaciones coincidentes

country   year valor1 valor2  
1 Argentina 2000 100    91.65267

In [351]:
merge(data1, data2, by = c("country", "year"), all.x = TRUE)

country   year valor1 valor2  
1  Argentina 2000 100    91.65267
2  Bolivia   2024  75          NA
3  Brasil    2020 120          NA
4  Chile     2021  90          NA
5  Colombia  2021 110          NA
6  Ecuador   2022  80          NA
7  México    2023 115          NA
8  Paraguay  2024 125          NA
9  Perú      2022 105          NA
10 Uruguay   2023  95          NA

In [352]:
merge(data1, data2, by = c("country", "year"), all.y = TRUE)

country   year valor1 valor2  
1  Argentina 2000 100    91.65267
2  Argentina 2001  NA    54.66596
3  Argentina 2003  NA    40.31804
4  Argentina 2004  NA    16.13584
5  Argentina 2006  NA    66.56945
6  Brasil    2000  NA    62.21677
7  Brasil    2002  NA     6.78937
8  Brasil    2003  NA    20.57673
9  Brasil    2005  NA    80.53844
10 Brasil    2006  NA    17.99815
11 Chile     2001  NA    43.41373
12 Chile     2002  NA    26.82483
13 Chile     2004  NA    83.36083
14 Chile     2005  NA    55.13579
15 Chile     2020  NA    63.67248

In [337]:
merge(data1, data2, by = c("country", "year"), all = TRUE)

country   year valor1 valor2  
1  Argentina 2000 100    91.65267
2  Argentina 2001  NA    54.66596
3  Argentina 2003  NA    40.31804
4  Argentina 2004  NA    16.13584
5  Argentina 2006  NA    66.56945
6  Bolivia   2024  75          NA
7  Brasil    2000  NA    62.21677
8  Brasil    2002  NA     6.78937
9  Brasil    2003  NA    20.57673
10 Brasil    2005  NA    80.53844
11 Brasil    2006  NA    17.99815
12 Brasil    2020 120          NA
13 Chile     2001  NA    43.41373
14 Chile     2002  NA    26.82483
15 Chile     2004  NA    83.36083
16 Chile     2005  NA    55.13579
17 Chile     2020  NA    63.67248
18 Chile     2021  90          NA
19 Colombia  2021 110          NA
20 Ecuador   2022  80          NA
21 México    2023 115          NA
22 Paraguay  2024 125          NA
23 Perú      2022 105          NA
24 Uruguay   2023  95          NA

### Ejercicios data frames
1) Usando el dataset `mtcars`:
    * Muestra las 5 primeras filas
    * Presenta un resumen del datasest
    * Haz una copia del dataset y:
        * Convierte la variables "cyl", "gear" y "carb" en factores
        * Convierte las variables "vs" y "am" en lógicas
        * Muestra solo los coches con una potencia ("hp") mayor a 100
        * Crea un nuevo data frame llamado coches_seleccionados que incluya solo las columnas "mpg", "cyl", "hp" y "qsec" del dataset
        * Calcula el resumen estadístico (media, mediana, desviación estándar, etc.) de la columna "mpg" (millas por galón) para todos los coches en el dataset
        * Idem para "cyl" (número de cilindros)
        * Calcula la cantidad total de coches para cada valor único en la columna "cyl" (número de cilindros)
        * Encuentra el modelo de coche con la mayor potencia ("hp") y muestra su información completa
        * Calcula el promedio de potencia de los coches con 8 cilindros
2) Usando el dataset `Cars93` del paquete `MASS` y el dataset `mtcars`:
    * Agrega una columna al dataset de `mtcars` que contenga la marca y modelo de cada coche
    * Combina los dos dataset por modelo y marca del coche solo para aquellos modelos presentes en ambos datasets. ¿Coinciden los demás valores?
3) Supongamos que tienes dos dataframes con información sobre estudiantes de dos cursos diferentes. Cada data frame contiene tres columnas: "Nombre", "Edad" y "Promedio".
<pre>
curso_a <- data.frame(
    Nombre = c("Juan", "María", "Carlos"),
    Edad = c(20, 22, 21),
    Promedio = c(85, 92, 78))
</pre><pre>
curso_b <- data.frame(
       Nombre = c("Ana", "Luis", "Sofía", "Lourdes"),
       Edad = c(19, 23, 20, 21),
       Promedio = c(88, 90, 85, 80))
</pre>
* Combina los dos dataframes en uno solo llamado todos_los_estudiantes
* Agrega una nueva columna llamada "Curso" al dataframe todos_los_estudiantes que indicar a qué curso pertenece cada estudiante ("A" o "B")